### ISSUE TITLE
Unsetting the filter of missing values in the filter dialog not working

### ISSUE THREAD

**Issue by lehnerchristian** [lineupjs/lineupjs#101]
* Release number or git hash: 
 * Web browser version and OS: Linux 18.04, Firefox & Chromium

### Steps to reproduce

 1. set a filter with the filter dialog in a numerical column
 2. try unsetting the filter again

### Observed behavior
 * Filter cannot be unset in the filter dialog, because the checkbox is deactivated (using the sidebar it can be unset) --> see also the gif below

### Expected behavior
 * Filter should be unset

![lineup_disabled_filter](https://user-images.githubusercontent.com/1711080/48134740-2a29f080-e29b-11e8-925d-9c4d926ae154.gif)

**Comment by sgratzl** [comment]
in dev version part of #60

**Comment by thinkh** [comment]
Fixed for LineUp v3 with [v3.2.0](https://github.com/lineupjs/lineupjs/releases/tag/v3.2.0).
