### ISSUE TITLE
Use DOI to reveal elements of aggregated grouping

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#104]
Let’s suppose we want to look at the top soccer scorers in every league. How would we do that right now?

We could have a mode where a group is aggregated, but we have a degree of interest function, that reveals some of its members in detail and still show the aggregate of the rest of or the whole of the group. Here is a sketch:

![image](https://user-images.githubusercontent.com/2039375/48751435-96b0d200-ec41-11e8-8dfc-4eaac989c14d.png)

Katharina was able to manually achieve this using selections: 

![image](https://user-images.githubusercontent.com/2039375/48751446-a03a3a00-ec41-11e8-89ab-ab31b278f68c.png)

While the definition of the DOI function could be arbitrarily complex, I'd say we show the first N (e.g., 5, or a variable number) members of a group according to a sorting, and let the sorting be our DOI. 

In practice, this could be done by adding an additional glyph next to the > icon on the group. Alternatively, this could be the default, and we could add a "show more" and "show all" row at the bottom of a group.

That would significantly strengthen our arguments about Context + Detail in the paper, so if this is not unreasonably much work, I'd like to include it before the submission.

**Comment by sgratzl** [comment]
questions and comments:
 * how to ensure that the user understands that the summary is still the overall summary and not all except the 5 ones shown in detail?
 * I wouldn't make it a default, since the default that everything is aggregated is already used in the wild. Thus it would confuse existing users that already use the group and aggregation feature
 * since having no grouping = 1 group. is just a special case of having a grouping (N groups), it implies that a similar feature would be needed for the general case, i.e. show just the overall top 5.
 * if you are just interested in the top 5 of each group, why is the aggregation of the whole group needed then?
 * so far the data will be first filtered and then sorted which results that a filter cannot use the current rank of the item to filter the item. If I switch the order (first sort all, then filter out) the order criteria could be incorporated, however the performance is worse, since the whole dataset needs to be sorted all the time.

**Comment by sgratzl** [comment]
looks confusing to me

![2018-11-20 14_16_29-window](https://user-images.githubusercontent.com/4129778/48776558-7c720500-ecd0-11e8-9d83-f5e48a69a6f6.png)

**Comment by alexsb** [comment]
> questions and comments:
> 
> * how to ensure that the user understands that the summary is still the overall summary and not all except the 5 ones shown in detail?

Probably by introducing some kind of hierarchy, so that it's obvious that there is a parent aggregate and children rows. 

> * I wouldn't make it a default, since the default that everything is aggregated is already used in the wild. Thus it would confuse existing users that already use the group and aggregation feature

I didn't mean the default aggregate, but the default un-aggregate. But that's open for discussion.

> * since having no grouping = 1 group. is just a special case of having a grouping (N groups), it implies that a similar feature would be needed for the general case, i.e. show just the overall top 5.

If the global group is aggregated and de-aggregated, then yes, I don't think anything speaks against that. 


> * if you are just interested in the top 5 of each group, why is the aggregation of the whole group needed then?

I'm not just interested in the top 5, but in a focus+context approach. Granted, a smart filter would also get me there, but that filter seems rather complicated.

> * so far the data will be first filtered and then sorted which results that a filter cannot use the current rank of the item to filter the item. If I switch the order (first sort all, then filter out) the order criteria could be incorporated, however the performance is worse, since the whole dataset needs to be sorted all the time.

I can't really help there, but since you clearly have a linear list of items, that must be possible somehow. 


Re current implementation screenshot: that's cool, but yes, confusing. I think the reason why it's confusing is because there is (a) no hierarchy and (b) no clear difference between aggregated and individual rows. Can you try giving the aggregates a light-gray background? That would be the least intrusive approach.

**Comment by sgratzl** [comment]
> Can you try giving the aggregates a light-gray background?

I don't wanna introduce a background color, since then when no top X are shown lineup is gray for no reason. Moreover, there is an option to activate an alternative gray background scheme that will conflict with that

**Comment by sgratzl** [comment]
what is max with group having different sizes? 

so far the user can decide for each group whether it is aggregated or not. having such a slider would imply that you make your decision for all groups at one. 

re background color: so far all renderers assume that the background is white thus changing the background color can have a negative influence on the perception especially of the ones which use brightness to encode the value.

**Comment by mstreit** [comment]
> so far the user can decide for each group whether it is aggregated or not. having such a slider would imply that you make your decision for all groups at one.

It would only be applied to the aggregated groups. And you are right, the max can be different from group to group. Another option would be to have a toggle button between 'show sample' (plus an optional slider to set the sample size) and 'show all' = detail / regular LineUp mode.
 
> re background color: so far all renderers assume that the background is white thus changing the background color can have a negative influence on the perception especially of the ones which use brightness to encode the value.

Hm, ok. Maybe we can think of some other encoding - like a border around the group and some more spacing?

**Comment by mstreit** [comment]
With this new mode we could cover setups like the one in the WeightLifter paper: http://data.caleydo.org/papers/2016_infovis_weightlifter.pdf (see Figures 6 & 7).

**Comment by sgratzl** [comment]
> With this new mode we could cover setups like the one in the WeightLifter paper: http://data.caleydo.org/papers/2016_infovis_weightlifter.pdf (see Figures 6 & 7).

to which specific feature are you referring to and how does showing the summary of a group and then the top X help with that?

**Comment by mstreit** [comment]
Aha ok, in Weightlifter the aggregated part at the bottom show the filtered rows. 
What I meant is showing the aggregated summary of the groups and fill the rest of the space with the top (or a user defined number of) samples from the groups.

**Comment by sgratzl** [comment]
what is the "rest of the space" in terms of X groups + when considering having the overview mode in which items go down to 1px?

**Comment by mstreit** [comment]
good questions. I need to think about this a bit.

**Comment by alexsb** [comment]
Re slider: I think that's a good idea, but I don't think we want to transition directly to non-grouped, the aggregate summary will always be there. 

Re un-even group sizes: I don't think that's a problem.

Re BG color: yes, the gray-scale encoding is a problem. Let's try a frame. 

Re weight lifter: I don't quite follow.

**Comment by mstreit** [comment]
re slider: yes, we should not transition to non-grouped.
re weight lifter: forget it :-)

@sgratzl, any other concerns?

**Comment by mstreit** [comment]
we have three states that we can mix: aggregated group, space-filling, fixed-item height.
so far, we discussed in this issue the possibility of showing the top X items in the aggregated group. maybe we could apply this in the space-filling mode as well. 
that could also be our default mode: show top X elements + space-filling (1 px per item minimum). for ranking tasks but also for keeping the context, this is definitely useful. opinions?

**Comment by sgratzl** [comment]
I disagree with the default mode since most people use lineup just as a fancy table. re X top items. Still don't know how to proper visualize the grouping of the group header and the top X items. Moreover changing the top X value, if it should be globally done the "slider" would have no effect until the user groups and aggregates something.

**Comment by mstreit** [comment]
@sgratzl, do you plan to integrate this in the near future? If not, that's fine, but I need to know this for finishing the layout mode descriptions in the paper.

**Comment by sgratzl** [comment]
I got lost, can anyone provide an sketch how it should look like and what should happen when the user clicks a certain button.

**Comment by mstreit** [comment]
To make the discussion easier, here is a conceptual sketch of the different detail levels (DOI) + the current modes and how they combine the levels. The suggested DOI mode is shown on the right.

![ink-image](https://user-images.githubusercontent.com/4129755/49591646-4a6acf00-f96f-11e8-8e99-cc287e9a8c5b.png)

**Comment by mstreit** [comment]
basis for discussion:

![ink-image](https://user-images.githubusercontent.com/4129755/49594442-2fe82400-f976-11e8-8fd3-7e1666ac3f59.png)

@sgratzl @alexsb @thinkh @katush, please provide feedback.

**Comment by thinkh** [comment]
Re https://github.com/lineupjs/lineupjs/issues/104#issuecomment-444918248: According to your suggestion, you have a minor mistake in your figure: The first group must have a minus icon instead of the plus icon, because the samples are visible.

Beside that, IMO having an arrow and a +/- icon at the same time is confusing.

Example: It is possible to expand the whole group (arrow down is visible), but still have the samples collapsed (plus icon is visible). From the semantic meaning this is contradicting (= open and closed at the same time).

Further, it seems that the user has to expand the samples for each group manually, right? Alternatively, we could add a checkbox to the side panel (similar to `Item <-> Overview`) to *Show samples for groups*?

**Comment by sgratzl** [comment]
> Beside that, IMO having an arrow and a +/- icon at the same time is confusing.

agreed



> Alternatively, we could add a checkbox to the side panel (similar to `Item <-> Overview`) to _Show samples for groups_?

not a fan as already discussed. Having a button or slider in the side panel that has just an effect when you group and aggregate the groups. if you start on a plain field and press the button what should happen? Moreover, it is inconsistent with the current aggregate button that is located in the summary header of the aggregate column.

**Comment by mstreit** [comment]
Ok makes sense, but please also provide constructive suggestions how to solve this in a better way.

**Comment by thinkh** [comment]
Two more ideas that we could discuss:

1. Add a "Show first 10 rows of group ..." link below a each group similar to this mockup. 
  The rows will be visible below and the link is named "Hide rows ...". 

![image](https://user-images.githubusercontent.com/5851088/49727000-91a6d780-fc6f-11e8-8391-d872b7c36cc9.png)

2. As space-saving alternative to the link we could add a button below the group arrow, which is only visible when the group is aggregated. I could not find a suitable icon that represents "examples" or "part of"... Any ideas?

![image](https://user-images.githubusercontent.com/5851088/49727504-bd768d00-fc70-11e8-93a5-f32aa116801c.png)

**Comment by mstreit** [comment]
Hm, yes option 1 is not bad but would take a lot of space. I like option 2 but also don't have a better suggestions for an icon.

**Comment by sgratzl** [comment]
current state:

![image](https://user-images.githubusercontent.com/4129778/49995530-b90de500-ff8c-11e8-897c-c4f06e16a91d.png)

![image](https://user-images.githubusercontent.com/4129778/49995538-c1662000-ff8c-11e8-8f0c-d483985885c4.png)

no idea how I should get a border around the whole group since it consists of multiple independent rows

**Comment by mstreit** [comment]
looks good.
re border and arrangement of elements: how about this?
![ink-image](https://user-images.githubusercontent.com/4129755/49998231-0b063900-ff94-11e8-984b-86b329c05f6e.png)

**Comment by sgratzl** [comment]
so far the rank column and the aggregate column (the one with the collapse buttons) are separated. I would have to merge them to implement the suggested behavior.

re count vs rank range: the question is how should it look like when it just shows the aggregated groups. Moreover, while count vs rank range is similar for the first group, it is different for all the others. e.g. in the example above: 35-68 will become just 33. thus more difficult to see which is the first rank and which is the last.

**Comment by mstreit** [comment]
ok. would adding a thicker brace (see sketch) in the aggregate column work?

**Comment by mstreit** [comment]
hm, not super sexy but I guess it's functional. 

@thinkh, @alexsb, @katush, any further suggestions?

for the future: I think merging the two columns would give us more freedom in terms of the positioning and layout. but that's not important for the paper.

**Comment by mstreit** [comment]
btw: the outer brace could span the full column width.

**Comment by mstreit** [comment]
another idea: instead of merging the two columns, you could render the number in the aggregate column and remove it from the selection column. however, this requires that the aggregate column and the selection column are always added next to each other by default.

**Comment by sgratzl** [comment]
I don't get it, in the screenshot you see three columns
 * AggregateGroupColumn -> collapse feature
 * RankColumn -> show column rank
 * SelectionColumn -> multi selection checkbox

**Comment by mstreit** [comment]
aha OK. can you try swapping the second and third column? this way the tree lines would look as they were connected to the selection boxes. might work better.

**Comment by thinkh** [comment]
Looks good. 👍  Here are some (minor) points:

1. I agree with @mstreit that we should try swapping the checkbox and rank column. Probably easy to test.
1. I would add more space between the arrow and the bold outer brace
1. I suggest to increase the space between the last top 10 row and the next group row. That would make it easier to distinguish the end/beginning between these two rows
1. If possible, suggest further to add a dummy row after the last top 10 row containing a "...", "24 more rows", or similar. Because at the moment the user can easily miss that the 10 rows are just a subset.

**Comment by sgratzl** [comment]
re swapping

with grouping criteria
![2018-12-14 15_54_05-lineup builder test](https://user-images.githubusercontent.com/4129778/50010118-e40e2e00-ffb8-11e8-8258-acb6b7471f07.png)

without
![2018-12-14 15_54_50-lineup builder test](https://user-images.githubusercontent.com/4129778/50010120-e4a6c480-ffb8-11e8-87d3-767dc5794f68.png)

**Comment by mstreit** [comment]
hm, not much better.
did you try to show horizontal lines per element that go through all three columns (and maybe only show them if the collapse column is present)?

**Comment by mstreit** [comment]
maybe replacing the tree thing with single bullet items could reduce the clutter. would look like a bullet list.
