### ISSUE TITLE
Group sorting hierarchy not working correctly

### ISSUE THREAD

**Issue by katush** [lineupjs/lineupjs#109]
Sorting groups by numerical values (median, mean) is not behaving correctly if the there is something above it in the hierarchy (e.g., group name/categorical attributes)

Example:
- group by Continent
- group by Ppl knowing they have HIV (split into 4 bins)
- sort groups by continent 
- sort groups by Ppl knowing they have HIV (descending, median)

The group with the highest median should be first, but is actually last.
![image](https://user-images.githubusercontent.com/8986080/49022677-b8f0a580-f195-11e8-80ee-68127faa3d44.png)

**Comment by mstreit** [comment]
@katush, please add the information with which deployed version you have tested this.

**Comment by katush** [comment]
Originally found in: LineUp.js v4.0.0-alpha.7 (20181115-103904)
Also present in current develop: 
group by Curren League
group by Age (split into 3 bins)
sort groups by Curren League
sort groups by  Age (descending, median)
The top 3 groups are clearly not sorted by median, even though the League name is the same
![image](https://user-images.githubusercontent.com/8986080/49023915-8bf1c200-f198-11e8-9282-91deba91957d.png)

**Comment by sgratzl** [comment]
according to the current implementation of how categorical groups are compared, it behaves correctly: 

https://github.com/datavisyn/lineupjs/blob/d06c42af30281f08aa461790655a7a87c03ef06e/src/model/ICategoricalColumn.ts#L112-L134

i.e find the most frequent category, compare them, if they are the same, sort by frequency of most frequent one

**Comment by mstreit** [comment]
@sgratzl, OK, but is there a reason why it needs to use the frequency only for the comparison and not use whatever the user has specific in the 'sort group by' dialog?

**Comment by sgratzl** [comment]
it does use what is in the hierarchy. However, according to this implementation, the first sorting criteria is already enough to sort the groups thus the second one has no effect

**Comment by katush** [comment]
To be clear 'sort groups by' on categorical column means 'sort groups by frequency of categories'? I didn't know that (and I don't think it's very clear), but I get what happend now.

**Comment by mstreit** [comment]
Aha, yes. I think it would be useful to let the user decide what the grouping criteria should be. Now the default for categorical categories is obviously frequency (number of items). I can think of cases where I would like to sort alphabetically by the category name.

Loosely related: For the group sorting of numerical columns the user can select the statistical measures, which is great. Sorting by frequency (number of items) would also be useful, right?
![image](https://user-images.githubusercontent.com/4129755/49025442-f821f500-f19b-11e8-81d0-b483a74255e5.png)

**Comment by sgratzl** [comment]
> . Sorting by frequency (number of items) would also be useful, right?

isn't that why there is the group column for? since why is the number of items in the field specific to a numerical column?

**Comment by sgratzl** [comment]
> Now the default for categorical categories is obviously frequency (number of items).

no it is the name and frequency of the most frequent category in the group. e.g. if you sort the group by a categorical attribute that is not the grouping criteria.

**Comment by mstreit** [comment]
> > . Sorting by frequency (number of items) would also be useful, right?
> 
> isn't that why there is the group column for? since why is the number of items in the field specific to a numerical column?

Oh yes, I forgot about that one because it is not added by default anymore. What was the reason to not add it by default? Too wide?

**Comment by mstreit** [comment]
> > Now the default for categorical categories is obviously frequency (number of items).
> 
> no it is the name and frequency of the most frequent category in the group. e.g. if you sort the group by a categorical attribute that is not the grouping criteria.

sorry, without an example I cannot follow anymore...

**Comment by katush** [comment]
The group column however doesn't contain the option to sort by number of items right now.

**Comment by mstreit** [comment]
> The group column however doesn't contain the option to sort by number of items right now.

You mean the 'Group Name' column? As @sgratzl said, it sorts by the number of items in the groups. (Correct me if I am wrong)

**Comment by katush** [comment]
So it doesn't actually sort by 'group name' as in the string it contains? Because thats wat I would expect when I click on sort by in column called group name.
And if that's not the case, can I actually sort by group name? Because I can imagine cases when I would want that.

**Comment by mstreit** [comment]
(@katush, I deleted your last comment because it was a reply to my already deleted comment).

**Comment by mstreit** [comment]
> > . Sorting by frequency (number of items) would also be useful, right?
> 
> isn't that why there is the group column for? since why is the number of items in the field specific to a numerical column?

How can I sort the groups by frequency? If it works, I am not aware of that feature. The 'Group Name' column sorts the groups alphabetically.

**Comment by mstreit** [comment]
@sgratzl, can you clarify my last question? I need to know this for the paper writing.

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/50681019-2a7c0900-100a-11e9-9945-60b12f357c61.png)

**Comment by mstreit** [comment]
OK

**Comment by sgratzl** [comment]
@thinkh please specify the desired behavior since there was no consensus in the previous discussion.

**Comment by thinkh** [comment]
Coming from issue #161, where we came to the same conclusion, I'd would perfer the implementation that @sgratzl showed in [this comment](https://github.com/lineupjs/lineupjs/issues/109#issuecomment-451392409).

> By what are categorical attribute groups sorting if they are NOT the stratification criteria?

I know it's a long time, but I cannot imagine a use case where this would make sense. In my opinion, group sorting requires enabled grouping in the first place. I would even suggest to hide the _Sort Groups by_ action and only show it when the column is grouped.

@sgratzl What is your opinion? Does this clarify your questions so that you can start implementing it?

**Comment by sgratzl** [comment]
> I know it has been a long time, but I cannot imagine a use case where this would make sense. In my opinion, group sorting requires enabled grouping in the first place. I would even suggest to hide the _Sort Groups by_ action and only show it when the column is grouped.

I'm not a fan of showing/hiding a button based on the state of the current column. And a use case in general is: group by categorical, sort groups by mean of a numerical.

**Comment by sgratzl** [comment]
closing in favor of #161
