### ISSUE TITLE
Use `getElementsByClassName()` for better performance

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#123]
Use `document.getElementsByClassName('classname')[0]` instead of  `document.querySelector('.classname')` for better performance.

![grafik](https://user-images.githubusercontent.com/5851088/50395651-b9189c80-0765-11e9-8c24-219f2b379cc2.png)

![grafik](https://user-images.githubusercontent.com/5851088/50395678-e9f8d180-0765-11e9-9940-55cf418b8f41.png)

Source: https://jsperf.com/getelementsbyclassname-vs-queryselectorall/212

The function `getElementsByClassName()` is available in all browsers (see https://caniuse.com/#search=getElementsByClassName).

**Comment by sgratzl** [comment]
thx. Tho I don't think it gives a lot of improvements since `.querySelector` is barely used when it comes to rendering rows and would therefore be executed very often in which it would make a difference

**Comment by thinkh** [comment]
Thanks for the fast adoption. 😃
