### ISSUE TITLE
Missing `setSplicer()` on `ArrayColumn`

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#124]
Coming from https://github.com/Caleydo/lineup_app/issues/44

After merging the most recent develop branch the split matrix feature does not work anymore.

It seems that the `setSplicer()` function was removed during a refactoring in
https://github.com/lineupjs/lineupjs/commit/2881a6a01460ee0f18186d26178cfc9f17dc65e7#diff-3f7d377ba0c45462eaf80c0e646c52b4L53.

@sgratzl Did you move the `setSplicer()` somewhere else? Or is there another way to repair the splice matrix feature?

**Comment by sgratzl** [comment]
yes it was removed since there was no way to trigger this function via the user interface. As an alternative one could create different Column Descriptions each having a different `accessor` method implementing the slicing of the underlying array

**Comment by thinkh** [comment]
I switched to a row accessor, but ran into problems.

It seems that I need to adapt the `dataLength` property on the ArrayColumn so that the heatmap renderer work correctly. Before the `splicer.length` was overriding the `dataLength` property (see https://github.com/lineupjs/lineupjs/commit/2881a6a01460ee0f18186d26178cfc9f17dc65e7#diff-3f7d377ba0c45462eaf80c0e646c52b4L70).

I cannot change the `dataLength` property from, because it's calculated automatically from the data and read-only. I tried a workaround to change `col.desc.dataLength` which is also not correct, because it changes the `desc` object of the original column (even though the column was cloned).

So I probably need one of the following solutions:

* Change the `desc` object of the clone/new column (or override it while cloning?)
* Set the `dataLength` property manually
* Deep copy of the `desc` object when cloning a column

Related to this I also need to update the data domain range, since the min/max value might be different.

A demo with a single row (for debugging) is online here: https://5c335fa5962d3800091beec3--caleydo-lineup.netlify.com/#aids

You can find my changes here: https://github.com/Caleydo/lineup_app/compare/taggle-demo...Caleydo:thinkh/fix-split-matrix

@sgratzl Can you please help me here?

**Comment by sgratzl** [comment]
why not just
```ts
stratification.categories.forEach((group, i: number) => {
      const g = typeof group === 'string' ? {name: group, label: group} : group;

      const startIndex = stratification.colIndexRange[i][0];
      const endIndex = stratification.colIndexRange[i][1];
      const length = endIndex - startIndex;

      const groupDesc = Object.assign({}, this.desc, {
        label: g.label || g.name,
        dataLength: length,
        accessor: (row: IDataRow, desc: any) => row.v[desc.column].slice(startIndex, endIndex)
      });
      const gcol = <MatrixColumn>provider.create(groupDesc);
      gcol.setWidth(w * length / totalLength);
      base.push(gcol);
    });
```

**Comment by thinkh** [comment]
Thanks for your help. Now it works. 

I assumed that I must clone the column and then modify it. Creating a new one from the cloned description only is neat. 😃
