### ISSUE TITLE
Missing MappingFunction exports in v4.0.0-alpha.10

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#128]
Due to refactorings in https://github.com/lineupjs/lineupjs/commit/d82256025893119f06f7e6c4d9267e8e024c5d65#diff-a34274efa25ffe19e83c3763b4ae5abbL11 some exports, such as [createMappingFunction()](https://github.com/lineupjs/lineupjs/blob/develop/src/model/MappingFunction.ts#L192) or [ScaleMappingFunction](https://github.com/lineupjs/lineupjs/blob/develop/src/model/MappingFunction.ts#L57), are missing.

They are required for custom implementations in tdp_core ([here](https://github.com/datavisyn/tdp_core/blob/lineupjs4/src/lineup/internal/column.ts#L4) and [here](https://github.com/datavisyn/tdp_core/blob/lineupjs4/src/lineup/internal/cmds.ts#L7)).

**Comment by sgratzl** [comment]
with the latest develop branch classes such as `ScaleMappingFunction` and `ScriptMappingFunction` are now exposed
