### ISSUE TITLE
Bands for comparison of two table ranking not working

### ISSUE THREAD

**Issue by katush** [lineupjs/lineupjs#130]
When comparing two table snapshots with different rankings and groupings there used to be band visualization for group subsets:
![figure8](https://user-images.githubusercontent.com/8986080/51928685-bfe69f00-23f6-11e9-88dd-88da3fe37d88.png)
This is no longer present:
![image](https://user-images.githubusercontent.com/8986080/51928724-da207d00-23f6-11e9-9688-fc8a3ba9c0db.png)

Version:
https://taggle.caleydoapp.org/ - LineUp.js v4.0.0-alpha.10
Not sure if this is known or even fixable.

**Comment by mstreit** [comment]
Did you try https://lineup.js.org/app_develop/?

**Comment by katush** [comment]
@mstreit It's same there as well.

**Comment by mstreit** [comment]
Did you try clicking on the band icon that is shown in the middle at the top?
![image](https://user-images.githubusercontent.com/4129755/51929514-ae05fb80-23f8-11e9-8c0e-995ee4b1dc6c.png)

**Comment by katush** [comment]
No. now I feel stupid :D It's not possible to get the combination of it as before though, correct?

**Comment by mstreit** [comment]
Don't worry, the icons can be missed easily. No, the hybrid thing does not work anymore.
