### ISSUE TITLE
Cannot change column color

### ISSUE THREAD

**Issue by keckelt** [lineupjs/lineupjs#131]
* Web browser version and OS: Firefox 65 & Chrome 72 on Manjaro
Tested with: https://lineup.js.org/app/#soccer

Numerical column header:  _rename + color_ > change color > nothing happens.
Rename works.

Gif (from Firefox):
![lineup_recolor](https://user-images.githubusercontent.com/10337788/52045132-1ad9dc80-2544-11e9-9c3c-ba3eab38076a.gif)

**Comment by keckelt** [comment]
Chrome: 
![lineup_color_chrome](https://user-images.githubusercontent.com/10337788/52045331-976cbb00-2544-11e9-8aab-57b237e852fa.gif)

**Comment by thinkh** [comment]
The column color does not change the bar color anymore. Use the *color mapping* instead. 

However, you are right, we should remove the color from the dialog you showed. 😉

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/52046397-e9aedb80-2546-11e9-969a-06df726cf566.png)

-> develop is already like that. 

wontfix
