### ISSUE TITLE
Overview is unnecessarily compact

### ISSUE THREAD

**Issue by mstreit** [lineupjs/lineupjs#135]
* Release number or git hash: https://lineup.js.org/app_develop/#soccer
 * Web browser version and OS: Chrome

### Steps to reproduce

1. Load soccer dataset
2. Switch to overview
3. Filter Position: CF

### Observed behavior
 * I expected that the overview is space filling but the row height seems to stay at 1px even if there is more space after setting the filter. Or is that the expected behavior?

![image](https://user-images.githubusercontent.com/4129755/52358962-37d94880-2a39-11e9-855a-6c64395d741a.png)

### Expected behavior
Space filling overview (if enough items are available).

**Comment by sgratzl** [comment]
well 2px is too big and there are no 1.5px on the screen without strange artifacts

**Comment by mstreit** [comment]
aha OK, makes sense. I guess that's also the reason why I get rendering artifacts when the browser's zoom level is != 100%.
