### ISSUE TITLE
How to use a date column?

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#139]
I would like to create a date column with v4.0.0-alpha.10 and modified the random example. You can find my test on [codesandbox.io](https://codesandbox.io/s/j1lo06lm99).

Basically I added another function to create a random date and added the value to the data array:

```ts
function randomDate(rangeOfDays, startHour, hourRange) {
  var today = new Date(Date.now());
  return new Date(
    today.getYear() + 1900,
    today.getMonth(),
    today.getDate() + Math.random() * rangeOfDays,
    Math.random() * hourRange + startHour,
    Math.random() * 60
  );
}

// generate some data
const arr = [];
const cats = ["c1", "c2", "c3"];
for (let i = 0; i < 100; ++i) {
  arr.push({
    d: "Row " + i,
    a: Math.random() * 10,
    datetime: randomDate(100, 8, 24).toISOString(),
    cat: cats[Math.floor(Math.random() * 3)],
    cat2: cats[Math.floor(Math.random() * 3)]
  });
}
```

Then I added an additional column to the *dump.json*:

```json
        {
          "id": "col7",
          "desc": "date@datetime",
          "width": 200,
          "loaded": true,
          "filter": null,
          "groupCriteria": []
        }
```

Which results in the following warning:

![image](https://user-images.githubusercontent.com/5851088/52848360-cf602a80-310e-11e9-9f40-0242967cf0c3.png)

The column is **excluded** from the ranking.

If I switch the type of the new column to string the values are shown:

```json
        {
          "id": "col7",
          "desc": "string@datetime",
          "width": 200,
          "loaded": true,
          "filter": null,
          "groupCriteria": []
        }
```

![image](https://user-images.githubusercontent.com/5851088/52848423-f61e6100-310e-11e9-8e74-dfc7c9c0d033.png)

@sgratzl Could you please post a modified example, how to use the date column?

**Comment by thinkh** [comment]
I think I figured it out. The date column expects a JavaScript *Date* object and **not** a string.

Replacing `datetime: randomDate(100, 8, 24).toISOString()` with `randomDate(100, 8, 24)` did the trick.

![image](https://user-images.githubusercontent.com/5851088/52848930-3c27f480-3110-11e9-8e8d-92f1d1591418.png)

**Comment by thinkh** [comment]
I just tried adding `"dateFormat": "%d.%m.%Y"` to the JSON, but it does not change the format of the date in the ranking. How do I use this?

```json
        {
          "id": "col7",
          "desc": "date@datetime",
          "width": 200,
          "loaded": true,
          "filter": null,
          "groupCriteria": [],
          "dateFormat": "%d.%m.%Y"
        }
```

**Comment by sgratzl** [comment]
which json?

**Comment by thinkh** [comment]
The *dump.json* in my test on [codesandbox.io](https://codesandbox.io/s/j1lo06lm99).

**Comment by sgratzl** [comment]
but the dateFormat is not part of the dump since it cannot be configured interactively thus the date column is not dumping it

```
const lineup = LineUpJS.builder(arr)
  .deriveColumns()
  .column(LineUpJS.buildDateColumn("datetime").format("%d.%m.%Y"))
  .deriveColors()
  .restore(exportDump)
  .build(document.body);
```

**Comment by thinkh** [comment]
Ok, good to know. Thanks for the code example. 👍
