### ISSUE TITLE
Set column regex filters

### ISSUE THREAD

**Issue by eric-kimbrel** [lineupjs/lineupjs#150]
Feature request / enhancement

I would like to filter Categorical and Set columns with a regex filter similar to text columns.  For a set column a row with any value that matches the regex should be excluded (or included).  

If there is an existing way to implement this functionality please advise.

**Comment by sgratzl** [comment]
while there is no visual way to edit the filter yet, a categorical filter can be a string, an array of strings (default), or a regex. 

https://github.com/lineupjs/lineupjs/blob/790a0bbd36906539c27bae08ce517c27885ae56a/src/model/ICategoricalColumn.ts#L151-L154

thus, you can manually find the column and call `setFilter({filterMissing: false, filter: /test/gm})`

**Comment by eric-kimbrel** [comment]
Thanks! If that works I can just build some extra UI as a workaround for now.   Do you have any tips on how to access the column from the lineup instance returned by a DataBuilder?

**Comment by sgratzl** [comment]
take a look at https://codepen.io/sgratzl/pen/mogMPw?editors=0010
