### ISSUE TITLE
Provide JSON schema for JSON dump

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#151]
Exporting a JSON dump in v4.0.0 adds two JSON schema properties:

```json
{
 "$schema": "https://lineup.js.org/app_develop/schema.1.0.0.json",
 "type": "csv",
 "name": "Soccer Stats",
 "dump": {
  "$schema": "https://lineup.js.org/develop/schema.4.0.0.json",
  }
}
```

While the first schema [is available](https://lineup.js.org/app_develop/schema.1.0.0.json) the second [is not](https://lineup.js.org/develop/schema.4.0.0.json).

Hence, a JSON schema for the dump should be created. See the [official documentation](https://json-schema.org/) (currently in draft) for more information. Examples for JSON schemas are available at [vega](https://github.com/vega/schema).

**Comment by thinkh** [comment]
I suggest to follow Vega's schema URL format and put all schemas under `schema`: 

```
https://lineup.js.org/schema/[version].json
```

**Comment by sgratzl** [comment]
the schema does exist: https://github.com/lineupjs/lineupjs/blob/develop/src/provider/schema.json however, the website doesn't contain the develop builds anymore thus not having this file.

**Comment by sgratzl** [comment]
I changed the circle ci config such that it deploys the develop version, too. Thus https://lineup.js.org/develop/schema.4.0.0.json exists
