### ISSUE TITLE
loading.svg shown above image in image cells

### ISSUE THREAD

**Issue by einbandi** [lineupjs/lineupjs#157]
* Release number or git hash: 4.0.0-alpha.11
 * Web browser version and OS: Tested in Google Chrome v74.0.3729.169 and Firefox v66.0.5

### Steps to reproduce

 1. create a link column with image links and `renderer: 'image'`

### Observed behavior
* even if the image is found, the `loading.svg` is still shown on top of the image (see image below)
* the problem seems to be connected to `.lu-renderer-image:not(.lu-missing)::before`. maybe `lu-missing` is assigned to the image cell even when the image is in fact not missing

### Expected behavior
* `loading.svg` should not show when the image link works.

### Example image

![lineup-image-bug](https://user-images.githubusercontent.com/11440522/58187715-9e683680-7cb7-11e9-90b8-119e0eaf1f21.PNG)

**Comment by sgratzl** [comment]
fixed with https://github.com/lineupjs/lineupjs/commit/656229855364834ae6b5966c16a2cf1504cf6091 and will be part of LineUp.js 4
