### ISSUE TITLE
Grouping of 3+ categorical attributes is broken in v4.0.0-alpha.11

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#160]
* Release number or git hash: v4.0.0-alpha.11
 * Web browser version and OS: Chrome 75

### Steps to reproduce

The example is taken from the [demo](https://github.com/lineupjs/lineupjs/blob/develop/demo/aggregate.html) and extended by a third category.

 1. Open https://codesandbox.io/embed/lineup-soccer-stats-60q5v

### Observed behavior

❌ No ranking is shown for LineUp **v4.0.0-alpha.11** and **three grouping criteria**. There are no erors available in the console.

![grafik](https://user-images.githubusercontent.com/5851088/59277149-f31c2300-8c5f-11e9-8ce2-900e8ea0fa19.png)

✔ Reducing only **two grouping criteria** works:

![grafik](https://user-images.githubusercontent.com/5851088/59277384-66259980-8c60-11e9-8287-933237f8a180.png)

✔ Using three grouping criteria works only for LineUp **v4.0.0-alpha.10**:

![grafik](https://user-images.githubusercontent.com/5851088/59277271-2e1e5680-8c60-11e9-8dc7-9c6c262dd913.png)

### Expected behavior

* The ranking should work for 3+ grouping criteria in LineUp v4.0.0-alpha.11

**Comment by thinkh** [comment]
@sgratzl According to the github project pipeline, you moved this issue to _done_. In which why is this issue done or solved?

**Comment by sgratzl** [comment]
cannot reproduce it with https://codepen.io/sgratzl/pen/WNvGrbB?editors=0010 so far

**Comment by thinkh** [comment]
I updated my codesandbox to use LineUp 4.0.0-alpha.12 and it works now.

https://codesandbox.io/s/bug-grouping-of-3-categorical-attributes-h7ogt
