### ISSUE TITLE
Allow `color` property in column description but show deprecated warning

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#174]
* Release number or git hash: c8dfb18
 * Web browser version and OS: Chrome

### Observed Behavior

Before PR #105, which introduced the new `ColorMappingFunction`, was possible to set the color in the description like this:

```ts
const colDesc = {
	type: 'number',
	name: 'age',
	color: '#FF0000'
}
```

PR #102 removed the `color` property from `Column` and setting the the `color` property in the column description is deprecated. Instead the new property `colorMapping` should be used.

```ts
const colDesc = {
	type: 'number',
	name: 'age',
	colorMapping: '#FF0000'
}
```

### Expected behavior

For backward compatibility it would be good if LineUp still accepts the `color` property, but provides a warning that the `colorMapping` should be used instead.
The functionality can be completely removed in a future version.

**Comment by sgratzl** [comment]
the LineUp builder already includes a compatibility mode. 

```ts
  /**
   * sets the column color in case of numerical columns
   * @deprecated use colorMapping instead
   */
  color(color: string) {
    return this.colorMapping(color);
  }
```

**Comment by thinkh** [comment]
Thanks for the tip. In my specific case tdp_core does not use the builder and receives (old) column descriptions from the provenance graph.
