### ISSUE TITLE
CircleCI build for master branch never finishes

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#178]
All PRs that are supposed to merge into the master branch (#163, #164, #171, #177) are waiting for CircleCI and will never finish. I assume that it setting in the repository configuration is not correct. See also https://circleci.com/docs/2.0/workflows-waiting-status/.

![grafik](https://user-images.githubusercontent.com/5851088/64969275-df5a0b80-d8a3-11e9-90f7-f30305bea59c.png)

@sgratzl Since I do not have permission could you please have a look into the repository settings?

**Comment by sgratzl** [comment]
fixed. No, idea where the second circle/ci check was coming from

**Comment by thinkh** [comment]
Thanks. 👍
