### ISSUE TITLE
Complex accessor not working correctly when having object attributes containing numbers

### ISSUE THREAD

**Issue by lehnerchristian** [lineupjs/lineupjs#187]
* Release number or git hash: 3.2.2 (seems to also be a problem in version 4)
 * Web browser version and OS: 

### Steps to reproduce

see https://github.com/lineupjs/lineupjs/blob/master/src/provider/ACommonDataProvider.ts#L7-L26

 1. create nested data where each item has a nested object with key value pairs, the nested objects need to have keys with numbers in them, e.g.

```
interface INestedDatum {
  b: number;
  b0: number; // access to this number won't work
}

interface IDatum {
  a: number;
  b: INestedDatum
}

type Data = IDatum[];
```

 1. create a columns with a complex accessor (e.g. `b.b`, `b.b0`, etc.)
 1. adding those columns to LineUp will end up in showing the results for simple and complex accessors except those complex accessors containing numbers in their name

see also https://codepen.io/lehnerchristian/pen/LYYPpLy

### Observed behavior
 * The column with the complex accessor containing a number in the key shows `undefined`

### Expected behavior
 * The column should simply show its data.
 * The intention to parse numbers out of the keys is likely to be used as array indices, but those should probably be encoded as `b.b[0]` instead of `b.b0`.
* Furthermore an accessor of `b.b0b` also won't work, because the regular expression only checks if there is a number anywhere in the accessor and not at the end

**Comment by sgratzl** [comment]
we might wanna switch to https://lodash.com/docs#get to avoid this kind of issues in the future

**Comment by thinkh** [comment]
Alternatively we could also [use plain JS function](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_get).
