### ISSUE TITLE
More ... dialog option is visible even though it has no elements

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#200]
* Release number or git hash: v3.2.2
 * Web browser version and OS: Chrome Version 76.0.3809.87 

### Steps to reproduce

 1. Create a custom column with a custom toolbar annotation `@toolbar('myToolbar`).
 1. Add the toolbar action with option `shortcut: 'only'`. 

### Observed behavior
Action is not within the `...` (correct), but the `...` is still visible even though no elements are in there. For other columns, without the custom toolbar addon, the `...` is not visible. 
![Peek 2019-11-04 09-50](https://user-images.githubusercontent.com/51900829/68108765-0ff41400-fee9-11e9-96e0-50c2b29eb33f.gif)

### Expected behavior
 * `...` is hidden if no elements are in there

**Comment by sgratzl** [comment]
can you create an example based on https://codesandbox.io/s/empty-cherry-ynh2f ?

**Comment by puehringer** [comment]
@sgratzl Follow up question. When `disableAdvancedRankingFeatures()` is used, the `...` menu is not visible even though some of my (custom) toolbars should in there. When enabling advanced features which appear in the menu, the `...` appears again. 
See [here](https://codesandbox.io/s/stupefied-chebyshev-rwmiu): uncomment any of the `disable...()` and you will see the `...`. Otherwise, you won't even though you should because of my custom toolbar actions. 
Note: this happens even though `shortcut: true`. It would be expected with `shortcut: 'only'`.

**Comment by sgratzl** [comment]
so far the disabling of features is a combination of hiding them via CSS and not rendering them. Especially in the more button case it is tricky proper handle all the different cases.

**Comment by thinkh** [comment]
I remove the `lineup: v3` label, as the implementation for v4 is sufficient.

@puehringer will have a look if this might be fixed with PR #267 and get back to you.

**Comment by puehringer** [comment]
With the toolbar changes in https://github.com/lineupjs/lineupjs/pull/267 and a proper configuration, this issue is resolved. I will close it now, as a fix for `lineup: v3` is not feasible.
