### ISSUE TITLE
Column order is not updated on ranking move event listener

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#214]
Adding a event listener for the `Ranking.EVENT_MOVE_COLUMN` returns only the moved column. Currently, there is no way to get the list of all columns with new order, because the LocalDataProvider is not updated at that time point.

Two possible options:

1. provide a `Ranking.getColumn()` which returns the updated columns
2. update the information directly in the LocalDataProvider before dispatching the event

**Comment by sgratzl** [comment]
what do you mean?

https://github.com/lineupjs/lineupjs/blob/1bcc842653e7758ed174577143f1ef7aa2709ab2/src/model/Ranking.ts#L542-L547

the event is fired after the column order has changed

**Comment by thinkh** [comment]
You're right it works as expected. To test it I created a [codesandbox example](https://codesandbox.io/s/lineup-soccer-stats-kucwz). I mainly added these event listeners:

```ts
const ranking = lineup.data.getLastRanking();
ranking.on(Ranking.EVENT_MOVE_COLUMN, (col, index, oldIndex) => {
  console.log(col, index, oldIndex);
  console.log(ranking.columns); // updated order of columns
});

ranking.on(Ranking.EVENT_REMOVE_COLUMN, (col, index) => {
  console.log(col, index);
  console.log(ranking.columns); // updated order of columns
});
```

**Comment by thinkh** [comment]
Unfortunately the ranking.columns is private. So we still would need a `getColumns()` to access the columns in the event listener.

https://github.com/lineupjs/lineupjs/blob/1bcc842653e7758ed174577143f1ef7aa2709ab2/src/model/Ranking.ts#L120

**Comment by sgratzl** [comment]
yeah but `.getColumns()` or `.flatColumns` isn't

**Comment by thinkh** [comment]
There is no `getColumns()`. But `.flatColumns` might work. I will have a look at it.

**Comment by sgratzl** [comment]
https://github.com/lineupjs/lineupjs/blob/1bcc842653e7758ed174577143f1ef7aa2709ab2/src/model/Ranking.ts#L507-L509 should work

**Comment by sgratzl** [comment]
https://github.com/lineupjs/lineupjs/blob/1bcc842653e7758ed174577143f1ef7aa2709ab2/src/model/Ranking.ts#L507-L509 should work

**Comment by thinkh** [comment]
Sounds good!

**Comment by thinkh** [comment]
This works!
