### ISSUE TITLE
Missing Sort Group By in StringColumn

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#225]
* Release number or git hash: v4.0.0-alpha.12
 * Web browser version and OS: any

### Steps to reproduce

 1. Group a StringColumn

### Observed behavior
Sort applies to rows within group, there is no way to sort the groups themselves (like in a CategoricalColumn). 

### Expected behavior
Sort group by similar to the CategoricalColumn option.

**Comment by sgratzl** [comment]
what is the sorting logic in case the user wants to sort groups by a string even tho it is not used as a grouping criteria?
