### ISSUE TITLE
Indicate the aggregation method for groupings

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#226]
* Release number or git hash: v4.0.0-alpha.12
 * Web browser version and OS: Chrome 79

### Steps to reproduce

 1. Open https://lineup.js.org/app_develop/#soccer
 1. Group by categorical column
 1. Collapse rows

![grafik](https://user-images.githubusercontent.com/5851088/72330787-65059080-36b7-11ea-9742-607b5b6ef2d0.png)

Not clear whether min, max, median, etc is used to create each cell the heatpmap visualization (or any other group visualization).

### Feature request

Improve setting of which values are used in row collapsed view in case of complex columns (boxplots and heatmaps). As first step we can extend the tooltip and state the aggregation method. However, we are open further (visual) options.

**Comment by sgratzl** [comment]
> tooltip

of the aggregated heatmap cell
