### ISSUE TITLE
Harmonize pop-ups and dialogs

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#229]
Currently, pop-ups (e.g., column filtering, etc) differ with respect to their (closing) behaviour: Ok/Apply/Reset vs instant vs mouse auto-hide vs mouse click outside to hide.

Please harmonize this according to the following ideas:

* Cancel/apply should be explicit (no auto-hide)
* On apply / cancel close whole menu
* Add labels to apply / cancel
* Apply instantly in the background when possible (e.g., filtering), however go back to previous state if setting is cancelled

**Comment by thinkh** [comment]
@rumersdorfer Please prepare a spreadsheet with all possible dialogs and its features/buttons for LineUp v4. We can talk about this in person.

**Comment by thinkh** [comment]
State of current discussion

* All dialogs should have cancel, reset, and apply button
* Outside click of the dialog is a reset + close
  * Maybe configurable to apply on outside click (for power user)
* Reset should always restore default values (e.g., default label, no filters, ...)
  * Example: Rename resets to the currently set name, but not the original name, whereas StringColumn filter clears the filter
* Live preview for filters should be available for all column types and should be configurable (enable/disable)
  * Example: the CategoricalColumn filter has no live preview whereas a NumberColumn filter works on mouse up
  * CategoricalColumn and StringColumn filter use debounce of 300-500 ms for onChange (instead of onBlur for input in string filter)

**Comment by sgratzl** [comment]
there are four data states:
 1. default: a default value for the edited value (e.g. the name in the column desc)
 2. before: the value before the dialog was opened (e..g the current name)
 3. entered: the value visible in the dialog i.e., that the user currently entered (e.g. a new name)
 4. current: the value that is currently stored and used

as far as I understood following actions exist:

```
click apply -> current = entered & close dialog
click cancel -> current = before & close dialog
click reset -> entered = default
click outside -> current = default & close dialog
enter value & live preview -> current = entered
```

right?

**Comment by thinkh** [comment]
> there are four data states:

Yes, looks correct to me.

> click apply -> current = entered & close dialog
> click cancel -> current = before & close dialog
> click reset -> entered = default

Yes.

> click outside -> current = default & close dialog

You are right according to our previous comment, but I think we were wrong and what we want is equal to the cancel behavior:

```
click outside -> current = before & close dialog
```



> enter value & live preview -> current = entered

True for the live preview and the dialog is open. However, once the dialog is closed the clicks apply as defined above.

```
enter value & live preview -> current = entered -> click apply -> current = entered & close dialog
enter value & live preview -> current = entered -> click cancel -> current = before & close dialog
enter value & live preview -> current = entered -> click outside -> current = before & close dialog
```

**Comment by thinkh** [comment]
> Maybe configurable to apply on outside click (for power user)

Additional point for the outside click: This should be configurable and by default behave like the _cancel_ action, but can be switched to the _apply_ behavior. From the implementation the outside click function can directly refer to the cancel or apply function.

**Comment by thinkh** [comment]
@sgratzl Please book your work for this issue on task _M2 LineUp UI improvements_.
