### ISSUE TITLE
Obtain grouping information

### ISSUE THREAD

**Issue by hcraT** [lineupjs/lineupjs#235]
Hi,
first of all thanks for this great library.

I would like to be able to obtain the groups defined by the user for other visualizations.

According to the documentation only highlight and selection events can be listened. I've checked the source of the library, the examples, the issues (here on github) and I can't find and obvious way to be able to obtain the grouping information as it is changed.

Is there a way to obtain the groups?

Thank you very much!

Kind regards.

**Comment by thinkh** [comment]
Hi @hcraT,

thanks for using LineUp and your request.

If I understand you correctly, you can retrieve the current groups from the ranking using [`getGroups()`](https://github.com/lineupjs/lineupjs/blob/master/src/model/Ranking.ts#L236-L238):

```ts
const ranking = provider.getFirstRanking();
console.log(ranking.getGroups());
```

Does that work for you?

**Comment by hcraT** [comment]
Hi @thinkh,
thanks for your help.

I was able to get the example working. I'm using javascript and not typescript so I needed to tweak a bit the example posted below for reference:

```js
const ranking = lineup.data.getFirstRanking();
ranking.on(LineUpJS.Ranking.EVENT_GROUP_CRITERIA_CHANGED, function (previous, current)  {
    console.log(ranking.getGroups());
});
```

While going through the library I've seen that other than `EVENT_GROUP_CRITERIA_CHANGED` there is `EVENT_GROUPS_CHANGED` . What is the difference (if any) between the two event types?

Thank again for the help.

Kind regards!

**Comment by thinkh** [comment]
`EVENT_GROUPS_CHANGED` is fired in `Ranking.setGroups()`, so when the groups itself are set:

https://github.com/lineupjs/lineupjs/blob/1f56c5957b50a376c4812a1f7d6de549ff1ced64/src/model/Ranking.ts#L218-L223

`EVENT_GROUP_CRITERIA_CHANGED` is fired in `Ranking.setGroupCriteria()`, so when one or multiple columns are added to the group hierarchy:

https://github.com/lineupjs/lineupjs/blob/1f56c5957b50a376c4812a1f7d6de549ff1ced64/src/model/Ranking.ts#L426-L451

**Comment by hcraT** [comment]
Thanks again!
