### ISSUE TITLE
Derive data properties (min-max, categories, ...) automatically

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#236]
* Release number or git hash: v4.0.0-alpha.12
 * Web browser version and OS: 

### Observed behavior
Without using the builder to derive columns, there is no way to tell LineUp (i.e. via a Column Description flag) to automatically compute min/max, categories, ...

### Expected behavior
As columns are often dynamically added, and LineUp computes statistics such as histograms on the fly, it may be possible to derive those properties automatically (if not set explicitly).

**Comment by dg-datavisyn** [comment]
Hi @sgratzl. 

We come across this issue in almost any of our apps. We need to pre-fetch the min/max and categories before feeding them into lineup. It would really help if the min/max/categories would be optional parameters that can be defined by the user but don't have to be defined. Lineup needs to iterate over the data at least once to be able to show the histograms in the column headers and in this course, it could set min/max/categories **only** in the case that they weren't already defined by the users in advance. This should only be a minor change. What are your thoughts on this?

Best,

Dominic
