### ISSUE TITLE
String  filter dialog checkbox does not  behave as expected

### ISSUE THREAD

**Issue by oltionchampari** [lineupjs/lineupjs#237]
The string filter dialog allows you to press the  **filter rows containing empty values** checkbox  even though the **use regular expression** checkbox is already checked.

![stringColumn.gif](https://images.zenhubusercontent.com/5cf50109d8501ed6b9d4b966/14f6a72e-2aea-4ade-b2fd-9eb1cb27c3cd)

Expected behavior:
The **filter rows containing empty values** checkbox should be disabled.

**Comment by sgratzl** [comment]
so far the filter logic / hierarchy is:
```
is filter missing checked?
  then -> filter for missing values
  else
    is the filter field empty?
      then -> no filtering
      else 
         is regex checked
         then -> interpret filter as regex
         else -> interpret as string filter
```

Thus atm when the user toggles the filter missing checkbox the input field + as regex is disabled. However, checking as regex doesn't influence whether the user can check the filter missing, since former just customizes the behavior of the search field. 
4. else ->

**Comment by thinkh** [comment]
In my opinion the filter for string columns should work analog to the filter of numercial und categorical columns where users can filter for specific categories or ranges AND filter out missing values. At the end the checkbox filter missing values should be independent from the input field and checkbox above.

![lineup-filter-missing-string](https://user-images.githubusercontent.com/5851088/77330967-5d4e1200-6d20-11ea-94a1-6cf746e7a7b5.gif)

@sgratzl Is it possible to implement it like this?

**Comment by thinkh** [comment]
I remove the `lineup: v3` label, as the implementation for v4 is sufficient.
