### ISSUE TITLE
Demo Observable with lineup.js component

### ISSUE THREAD

**Issue by mstreit** [lineupjs/lineupjs#242]
To boost the visibility of the LineUp library, it would be nice to create and share an Observable (https://observablehq.com/explore) that uses and demonstrates some LineUp capabilities.

@sgratzl @thinkh @puehringer, what do you think about this?

**Comment by sgratzl** [comment]
I played a bit:

https://observablehq.com/d/263233b4ec7d0793

shows the simple lineup example with synchronized selection that can be observed and manipulated

**Comment by sgratzl** [comment]
https://observablehq.com/@sgratzl/lineup-simple-example-with-observable-base

is the simplified version

**Comment by mstreit** [comment]
Looks good, thanks.
I suggest to add it to the LineUp.js.org website.

One minor comment: Would be nice to replace the default font with something non-serif.
