### ISSUE TITLE
Remove active column filter if column is removed

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#248]
* Release number or git hash: v3.3
 * Web browser version and OS: 

### Steps to reproduce and observed behavior

 1. Filter by any column (i.e. select category in CategoricalColumn)
 1. --> `n` out of `m` are shown
 1. Remove the column
 1. --> Still `n` out of `m` are shown

### Expected behavior
Active filter of a column should be removed when the column is removed.

**Comment by sgratzl** [comment]
note: works in v4
