### ISSUE TITLE
Create demo to test all available column types

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#249]
Add a new demo file that contains all available column types.

https://github.com/lineupjs/lineupjs/blob/1019f08034bbc64dba5a0f7a245e22dab2baa920/src/model/models.ts#L8-L41

* For basic types you can [use the builder](https://github.com/lineupjs/lineupjs/tree/lineup-v4/src/builder/column)
* For ArrayColumns you can have a look at the [multivalue.html](https://github.com/lineupjs/lineupjs/blob/lineup-v4/demo/multivalue.html)

**Comment by sgratzl** [comment]
re array-set types -> can also be built via a builder since most have an `asArray` or `asSet` method. e.g `buildStringColumn('test').asArray()`

**Comment by oltionchampari** [comment]
> re array-set types -> can also be built via a builder since most have an `asArray` or `asSet` method. e.g `buildStringColumn('test').asArray()`

Could you please provide some additional  information on the following columns:
* `composite` : How to correctly define it with the method `ranking.composite()`.
* All the `Map` Columns ( `numberMap`, `stringMap`, `categoricalMap`, ... ) : How they work, what kind of data they expect and and their purpose.

**Comment by sgratzl** [comment]
> `composite` : How to correctly define it with the method `ranking.composite()`.

there is no `.composite` method. You can find the available methods here: https://lineup.js.org/master/docs/classes/_builder_rankingbuilder_.rankingbuilder.html

re map: e..g https://codepen.io/sgratzl/pen/dyoVwLB?editors=1010

regarding data: one that can be understood by https://github.com/lineupjs/lineupjs/blob/1f56c5957b50a376c4812a1f7d6de549ff1ced64/src/model/MapColumn.ts#L48-L60

purpose: initial idea was to support simple nested table data structures like 2 or 3 key value pairs
