### ISSUE TITLE
Custom Category Colors for Categorical Columns

### ISSUE THREAD

**Issue by PatrickAdelberger** [lineupjs/lineupjs#250]
How can I define custom colors for the categories?

![image](https://user-images.githubusercontent.com/42137747/75862699-9e2cc800-5dff-11ea-98c4-8a83a5fb2cee.png)

**Comment by sgratzl** [comment]
see https://codepen.io/sgratzl/pen/vYOebEE?editors=1010

you have to define the column and not just define the categories as a string but actually as objects (name, color)
