### ISSUE TITLE
Inconsistent highlighting of menu icons for enabled actions

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#277]
* Release number or git hash: v4.0.0-alpha.12 with PR #265 
 * Web browser version and OS: independent

### Steps to reproduce

 1. Open the column menu
 1. Click the various dialogs

### Observed behavior

![lineup-inconsistent-menu-highlight](https://user-images.githubusercontent.com/5851088/77667072-09426800-6f82-11ea-82c0-531937c25f5c.gif)

* Some icons get highlighted when re-opening the more menu (e.g., Sort by, Group by)
* Some icons not highlighted at all (e.g., Sort Groups by, Visualization, Color Mapping, ...)
* Some icons get immediately highlighted after the user confirms the dialog (e.g., Filter)

### Expected behavior
 
I think that the highlight is a good indicator for the user that the default option has been changed; so we should keep this feature. However, we should unify the highlight at least for the most frequent dialogs (i.e., Filter, Sort by, Group by, Sort groups by). Icons should then be highlighted once the setting is different from the default value _and_ the change is applied. Click on reset and apply the change would color it black again.

Alternatively, we can highlight the icon immediately when the default value has changed and the user is still in the live preview (which is equal to the Filter operation in the screencast above).

If we want to make it even more consistent, we should apply this change to all dialogs (e.g., Rename, Color Mapping, Data Mapping, Edit Script, Visualization). However, I'm not sure, if this will confuse the user or if one can figure out this rule.

@sgratzl Which behavior do you prefer and is best to implement? Would it be possible to make it consistent for all dialogs? If a developer would add a custom dialog would could that rule be also applied?

**Comment by sgratzl** [comment]
so far it was just for the most common operation that are usually shown as a shortcut (sort, filter, group, [sort groups]) and have a strong influence on the ranking (filter, sort, ...). 

For all it is difficult cause it requires to always check whether it is different from the default. For the four current ones, it is implemented in https://github.com/lineupjs/lineupjs/blob/lineup-v4/src/ui/header.ts#L92. I wouldn't know how to do it in a generic way and whether the additional effort brings adds any useful additional information.

**Comment by thinkh** [comment]
Ok, thanks for the explanation. Then let's make it consistent for the most common operations that are now working slightly different.
