### ISSUE TITLE
Wrong behavior of data mapping dialog

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#285]
* Release number or git hash: 9d9c5deed03dae683cfe763821ce6a21e7c8a090
 * Web browser version and OS: Chrome 80

### Steps to reproduce

1. Open data mapping dialog of a numerical column
1. Shift + Click on point
1. Reset dialog

### Observed behavior

![lineup-reset-datamapping](https://user-images.githubusercontent.com/5851088/78393531-5067d300-75ea-11ea-9498-58656d736c9b.gif)

* There is no live preview when changing the settings. Is this on purpose?
* If one is clicking on a point with Shift + Click to specify exact values, it is unclear how to close the popup again
* Unclear how the `Remove Mapping Line` works
* `Reset to default values` doesn't reset domain min/max

### Expected behavior

The issues above should be adressed and fixed.

**Comment by thinkh** [comment]
@sgratzl Please book your work for this issue on task _M2 LineUp UI improvements_.

**Comment by sgratzl** [comment]
>     * There is no live preview when changing the settings. Is this on purpose?

not part of the list in https://github.com/lineupjs/lineupjs/pull/265#issuecomment-603853981
