### ISSUE TITLE
Improve data mapping dialog visualization

### ISSUE THREAD

**Issue by mstreit** [lineupjs/lineupjs#286]
The current mapping dialog visualization has room for improvement. 
![image](https://user-images.githubusercontent.com/4129755/78536930-e9ffd200-77ee-11ea-8664-6e3cd29e552e.png)

I suggest the following improvements:
- Add min/max of input and output domain directly above/below the starting points.
- Horizontal input/output domain lines should not have same style as draggable vertical connection lines, as those are very different things
- Try to make it clear that only the vertical lines and the two output domain points can be interactively changed by picking a different encoding. I suggest to color the draggable lines and points with one hue (e.g., using the selection color of lineup).

**Comment by thinkh** [comment]
Related to #285
