### ISSUE TITLE
update build system

### ISSUE THREAD

**Issue by sgratzl** [lineupjs/lineupjs#290]
* tslint -> eslint
 * use prettier
 * update typescript version especially to get rid of empty JS imports
 * use github actions instead of circleci (TODO how to update the website repo)
 * use yarn 2 pnp ?
 * create proper .esm build
 * find way to merge the declaration files, e..g https://github.com/chitter99/typescript-declaration-webpack-plugin

**Comment by thinkh** [comment]
In general the changes sound necessary and good. 

> * use yarn 2 pnp ?

What would be the advantage of yarn 2 pnp? 

> find way to merge the declaration files, e..g chitter99/typescript-declaration-webpack-plugin

What is the advantage of a single declaration file?

**Comment by sgratzl** [comment]
> What would be the advantage of yarn 2 pnp?

you have ONE `.pnp.js` file and just the zip files of the dependencies. Thus, the `yarn install` is very fast and less of a burden on your hard drive. Moreover, it enforces that you are just allowed to use the dependencies you are actually declared. IDE support is currently in development, especially the opening of ZIP files is not yet possible but will be soon.

**Comment by thinkh** [comment]
Ok, sounds interesting. I assume that we can still use the published lineupjs build still as usual via npm?

**Comment by sgratzl** [comment]
it has influence on the built files. I used it recently in a monorepo together with yarn workspaces and it had speed up the installation time a lot.
