### ISSUE TITLE
Item sorting influences group sorting, but should not

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#291]
* Release number or git hash: 4.0.0-alpha.12
 * Web browser version and OS: independent

### Steps to reproduce

1. Open grouping.html 
1. Remove all sorting and grouping from hierarchies
1. Sort number column in descending order
1. Group by _cat2_
1. Group by _cat_
1. Collapse second level grouping
1. Sort groups of _cat_ in descending order
1. Open first group
1. Sort number column in ascending order
1. Toggle the item sorting a few times

### Observed behavior

![lineup-item-sorting](https://user-images.githubusercontent.com/5851088/78649526-d8d1c680-78bd-11ea-825a-a89744cb89e5.gif)

Sorting the items (after the sorting groups) orders all groups differently and seems to follow the item sorting. Toggling the item sorting a few times afterwards is only sorting the items within the groups (which is the expected behavior). However, the group sorting is never restored.

### Expected behavior

Item sorting should not influence the group sorting and only sort items within the groups. Group sorting should only arrange whole groups.

**Comment by sgratzl** [comment]
can you create a cypress test, please

**Comment by thinkh** [comment]
I'll try... 😄

**Comment by thinkh** [comment]
@sgratzl I created a cypress test in branch https://github.com/lineupjs/lineupjs/tree/thinkh/291_item-sorting-influence. Not sure about the file naming convention and the selectors itself. Please feel free to revise it.
