### ISSUE TITLE
How to use a (static) link text when the value is an URL?

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#306]
* Release number or git hash: v4.0.0-beta.1
 * Web browser version and OS: any

The link column takes a row value and pattern to generate a hyperlink. This could look like in the _all_columns_type.html_ demo:

![grafik](https://user-images.githubusercontent.com/5851088/79548477-cb72c400-8095-11ea-8cbb-98998c3ce34f.png)

**Data and column desc**

* Values: Row 0, Row 1, ...
* Pattern: `https://duckduckgo.com/?q=${escapedValue}`

**Result**

* Link href: https://duckduckgo.com/?q=Row%200 , https://duckduckgo.com/?q=Row%201, ...
* Link text: Row 0, Row 1, ...

----

In my use case the value is already a valid URL and I want to use a static link text:

**Data and column desc**

* Values: http://dx.doi.org/10.1109/TVCG.2013.173, http://dx.doi.org/10.1177/1473871619878085, ...
* Pattern: `<empty>`

**Result**
* Link href: http://dx.doi.org/10.1109/TVCG.2013.173 , http://dx.doi.org/10.1177/1473871619878085 , ...
* Link text: http://dx.doi.org/10.1109/TVCG.2013.173, http://dx.doi.org/10.1177/1473871619878085, ...

Since the pattern is empty the link href and text are the same. However, what I would like to have is something like this:

![grafik](https://user-images.githubusercontent.com/5851088/79549059-b8142880-8096-11ea-8bb9-bd9f625863f2.png)

**Result**
* Link href: http://dx.doi.org/10.1109/TVCG.2013.173 , http://dx.doi.org/10.1177/1473871619878085 , ...
* Link text: Open Full Text, Open Full Text, ...

Is there any pattern or way to set/configure the link text independently of URL pattern?

**Comment by sgratzl** [comment]
have you tried passing the data in the `ILink` format? https://github.com/lineupjs/lineupjs/blob/lineup-v4/src/model/LinkColumn.ts#L22

**Comment by thinkh** [comment]
Thanks for the hint. Transforming each data value beforehand worked for this use case! 👍 

```ts
rows.map((row) => {
  row['doi_link'] = {
    alt: 'Open Full Text',
    href: row['doi_link']
  };
}
```
