### ISSUE TITLE
Wrong sorting of numerical columns (natural sorting)

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#311]
* Release number or git hash: v4.0.0-beta.1
 * Web browser version and OS: any

### Steps to reproduce

 1. Open _categories.html_
 1. Remove the `c` in the category name
    ```js
        const cats = (new Array(numCats)).fill(0).map((_, i) => `${i + 1}`);
    ```
 1. Open demo
 1. Group by categorical column

### Observed behavior

![grafik](https://user-images.githubusercontent.com/5851088/79861738-24fc2b00-83d5-11ea-993e-8a000eaa702d.png)

Category order
```
1, 10, 11, 12, 13, ..., 2, 20, 21, ..
```

### Expected behavior

Categories should be sorted naturally:
```
1, 2, 3, ..., 9, 10, 11, 12, 13, ..., 19, 20, 21, ...
```

A use case would be the chromosome number.

In case the category contains words the order should be sorted by alphabet (which is already works).

**Comment by sgratzl** [comment]
do you have an sort the groups the by the categorical attribute?

**Comment by thinkh** [comment]
Valid point! I forgot that. Now this works, but I found another bug. 😉 

1. Group categorical column
1. Sort groups by...
1. Select ascending -> groups are resorted
1. Cancel dialog -> the groups remain sorted

![lineup-sort-categorical-groups](https://user-images.githubusercontent.com/5851088/79862949-31818300-83d7-11ea-9e3e-4220932ff6a7.gif)

**Expected behavior**

The group sorting should be reset when the user cancels the sort group by dialog.

**Comment by thinkh** [comment]
In the following there is another broken example for the group sorting. In this case LineUp v4.0.0-beta.1 is integrated in tdp_core.

![ordino-group-sorting](https://user-images.githubusercontent.com/5851088/79866287-d2bf0800-83dc-11ea-97c0-0969afa795e7.gif)

The group sorting does not make sense at all.

**Comment by sgratzl** [comment]
> The group sorting does not make sense at all.

it does, it is exactly the order of the defined categories, i.e., the colors order matches the color order within the histogram.

**Comment by thinkh** [comment]
Yes, that might be. But as a user I would expect that the categories are ordered (naturally) by numbers. Could you change this please?

**Comment by sgratzl** [comment]
> Yes, that might be. But as a user I would expect that the categories are ordered (naturally) by numbers. Could you change this please?

as a developer of the lineup instance you intentionally set the order of the categories to this value. Why can't tdp_core just sort the categories to the desired ordering before handing it to LineUp?. Changing the LineUp logic will break the original problem of this issue, since it then will sort 1,10,2,... cause they are all strings and the natural order of strings is alphabetically.

**Comment by thinkh** [comment]
Thanks for the explanation. I get your point now and found some code in Ordino (which I was not aware of) that sorts, e.g., the chromosome beforehand. Since the code is open source, I post the links here. Maybe that helps somebody later.

The database returns a sorted, but not naturally sorted array of chromosomes:

```json
{
  "type": "categorical",
  "label": "chromosome",
  "column": "chromosome",
  "categories": [
    "1",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "2",
    "20",
    "21",
    "22",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "MT",
    "X",
    "Y"
  ]
}
```

When getting the categories (i.e., chromosomes) we are [sorting them manually](https://github.com/Caleydo/tdp_publicdb/blob/920738ffb3b08a5274dd5d90e055473ace0f5414/src/config.ts#L181) again:

```ts
categoricalCol('chromosome', toChromosomes(find('chromosome').categories), {label: 'Chromosome'}),
```

The [custom sort function `toChromosomes()`](https://github.com/Caleydo/tdp_publicdb/blob/920738ffb3b08a5274dd5d90e055473ace0f5414/src/config.ts#L138-L165
) looks like this:

```ts
function toChromosomes(categories: string[]) {
  const order = new Map<string, number>();
  for (let i = 1; i <= 22; ++i) {
    order.set(String(i), i);
  }
  order.set('x', 23);
  order.set('y', 24);
  order.set('mt', 25);

  categories.sort((a, b) => {
    const an = a.toLowerCase();
    const bn = b.toLowerCase();
    const ai = order.get(an);
    const bi = order.get(bn);
    if (ai === bi) {
      return an.localeCompare(bn);
    }
    if (ai == null) {
      return 1;
    }
    if (bi == null) {
      return -1;
    }
    return ai - bi;
  });

  return categories.map((d, i) => ({name: d, label: d, value: i}));
}
```

I will test your PR for the bug I posted above. Then we can close this issue.
