### ISSUE TITLE
Stacked bar renderer numbers overlap when hovering the bars

### ISSUE THREAD

**Issue by oltionchampari** [lineupjs/lineupjs#319]
* Release number or git hash: 
 * Web browser version and OS: Chrome  81.0.4044.129 / Ubuntu

### Steps to reproduce

 1. Add a weighted sum column
 1. Choose the renderer  to be the stacked bar renderer

### Observed behavior
 * For very low values the rows' values show on top of each other
### Expected behavior
 * The column values should not overlap

![weighted_column_bug.gif](https://images.zenhubusercontent.com/5cf50109d8501ed6b9d4b966/3b29b98e-2e0e-4b2d-bf2f-47d9df37a793)

**Comment by sgratzl** [comment]
>     * The column values should not overlap

how should they look then if they are not overlapping but one still knows which number corresponds to which bar?

**Comment by thinkh** [comment]
Instead of overplotting the numbers, it might be better to show them next to each other, and only if the bar is wide enough, the number can be displayed inside the bar.

I'm aware that this feature might be difficult to implement, as it contains a lot of testing and edge cases, but it would definitely improve the usability and readability.

**Comment by sgratzl** [comment]
one could
 * determine the text with either using canvas ctx.measureText or via a CSS helper box - for both the proper font and font-size needs to be determined + it is costly. assuming we are dealing only with numbers, we could compute for `.0123456789NaN` individually once and then guess. might not be perfect probably good enough
 * hide the labels within the individual bars and add one label below the stacked bar manually.Tho, I have no idea how to create an adaptive text block for the label (e.g. 10px white text, 10px dark text, 10px white....)

**Comment by thinkh** [comment]
> determine the text with either using canvas ctx.measureText or via a CSS helper box - for both the proper font and font-size needs to be determined + it is costly. assuming we are dealing only with numbers, we could compute for .0123456789NaN individually once and then guess. might not be perfect probably good enough

I think for now we are only dealing with numbers, as they are the once who can be stacked and overlap.

> hide the labels within the individual bars and add one label below the stacked bar manually.Tho, I have no idea how to create an adaptive text block for the label (e.g. 10px white text, 10px dark text, 10px white....)

CSS filter might help you in this case. See example on [CSS Tricks](https://css-tricks.com/methods-contrasting-text-backgrounds/):

```css
filter: invert(1) grayscale(1) contrast(9)
```

![CSS Tricks](https://i0.wp.com/css-tricks.com/wp-content/uploads/2017/06/select_text_method0.gif?ssl=1)

**Comment by sgratzl** [comment]
interesting, if I should implemented it, I need to be assigned first
