### ISSUE TITLE
small correction for text on github readme

### ISSUE THREAD

**Issue by Fpadt** [lineupjs/lineupjs#330]
Hi Samuel,

for the support of R the github page indicates:
_devtools::install_github("rstudio/crosstalk")
devtools::install_github("lineupjs/lineup_htmlwidget")
**library(lineup)_**

the library should however be 
**library(lineupjs)**

amazing package though, thanks a lot

**Comment by sgratzl** [comment]
thx for the hint

**Comment by thinkh** [comment]
@Fpadt Thanks for the hint. We fixed the typo. It will be release with the next LineUp version.
