### ISSUE TITLE
Prepare LineUp v4.0.0 release

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#331]
We are almost done with integration and testing of LineUp v4.0.0 in our apps. Hence, we would target a release in the next weeks. The goal would be to prepare everything so that it can be released once we are done.

@sgratzl Is there anything from your side that you need to prepare before the release? Can you please prepare a checklist with steps that we/you can follow on the release day?

**Comment by sgratzl** [comment]
not much has changed since the last beta and dependent libraries like lineupjsx won't jump to a new major version automatically

**Comment by thinkh** [comment]
Ok, sounds good. Will you release a new version of these wrappers afterwards? (For us they are not critical though.)

**Comment by sgratzl** [comment]
as you like

**Comment by thinkh** [comment]
> as you like

You can update and release the other repos and wrappers afterwards. They are not time critical for us.

As for the schedule, we are planning to release LineUp 4 at the beginning of next week.  

In my opinion there are the following steps to do/open:

- [ ] Please review and merge PR https://github.com/lineupjs/lineupjs/pull/345
- [ ] Create a last LineUp v3 release from current develop branch (if there are unreleased commits)
- [ ] Merge `lineup-v4` branch into `develop` branch
- [ ] Release LineUp v4
- [ ] Prepare next LineUp v4 develop branch

**Comment by thinkh** [comment]
@sgratzl Please release LineUp v4 and make it the default `develop` branch. Please keep a `lineup-v3` branch as described above as backup. Thanks!

**Comment by thinkh** [comment]
@sgratzl Thanks a lot for your work and the release! 🎉
