### ISSUE TITLE
Add "contains" category filter for `SetColumn`

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#332]
* Release number or git hash: v4-beta.1
 * Web browser version and OS: Chrome 83

### Steps to reproduce

1. Open _all_column_types.html_ demo
1. Filter a _SetColumn_ for a single category

### Observed behavior

![lineup-filter-setcolumn](https://user-images.githubusercontent.com/5851088/83872574-8a606d00-a732-11ea-8c73-9acc704d83a4.gif)

Filtering a _SetColumn_ for a single category does not show any row (or if there are any, it would only show the exact match with a single category).

### Expected behavior

There are two different use cases:

1. Exact match of all selected categories (current behavior)
2. Contains the selected categories

While the first use cases reflects the current behavior the seconde use case is not addressed. 

Would it be possible to a flag where the user can switch between exact match or contains?

**Comment by sgratzl** [comment]
>     1. Exact match of all selected categories (current behavior)

it is not an exact match but the filter is that: each category in the value has to be in the filter.

```js
return v.every((s) => isCategoryIncluded(this.currentFilter, s));
```

as far as I understood you are asking for a second option, which uses a `some` instead of any `every`, right?

```

**Comment by thinkh** [comment]
I tested the filter using `some` and it works like I would expect it in the second use case.

```ts
return v.some((s) => isCategoryIncluded(this.currentFilter, s));
```

Would you replace `every` with `some` or support both use cases?
I assume that the `some` use case is the more common one as it shows more results, but current behavior is also valid might be useful in some cases.
