### ISSUE TITLE
No removeDesc equlivalent to pushDesc in ACommonDataProvider

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#338]
* Release number or git hash: Release 4.0.0-beta.1
 * Web browser version and OS: 

### Observed behavior
 * You can use `provider.pushDesc(...)` to add a column description to a `LocalDataProvider` for example, but there is no way to remove a specific description from said provider. What is missing is a `removeDesc(...)` function (or is there an alternative to this?). 
* I also noticed that there is a type declaration for a function `addDesc(...)` which is defined nowhere. I guess it should be named `pushDesc(...)`: https://github.com/lineupjs/lineupjs/blob/develop/src/provider/ADataProvider.ts#L97-L101

### Expected behavior
 * A `removeDesc(...)` function including events which removes a column desc and fires the appropriate event.

**Comment by sgratzl** [comment]
>     * I also noticed that there is a type declaration for a function `addDesc(...)` which is defined nowhere. I guess it should be named `pushDesc(...)`: https://github.com/lineupjs/lineupjs/blob/lineup-v4/src/provider/ADataProvider.ts#L97-L101

those are event signatures

>     * What is missing is a `removeDesc(...)` function (or is there an alternative to this?).

removeDesc would need to make sure that there is no column that is actually using the description.

**Comment by puehringer** [comment]
Alright, I am still confused about `add|push` and their usages, but that makes sense. 
Regarding the `removeDesc`: removing an _active_ column is easy and can be done with the column instance or even from the ranking. How about removing the desc only if no column is active, i.e. returning a boolean? Or throwing an exception?

**Comment by sgratzl** [comment]
@thinkh so what is the plan?

**Comment by thinkh** [comment]
If I understand this correctly, someone would use it like this:

```js
const columnDesc = {
	type: 'string',
    column: 'mystring',
	label: 'My String',
};

const provider = lineup.data;
provider.pushDesc(columnDesc);

// later

const success = provider.removeDesc(columnDesc); // by object
const success = provider.removeDesc('mystring'); // by column property
```

Note that the `column` property is not part of the [`IColumnDesc`](https://github.com/lineupjs/lineupjs/blob/89d3e8a2d241e2a10d2a24f0ecc6bb5ae0e2329b/src/model/interfaces.ts#L77), even though it is used everywhere (e.g., [`findDesc`](https://github.com/lineupjs/lineupjs/blob/77d4339d6af501d9c956f06900f1b5b23531eb83/src/provider/ACommonDataProvider.ts#L60-L62)).
@sgratzl Could it be that the `column` property is missing in the `IColumnDesc` interface?

I'd also suggest a way to ask if any column instances are available before removing it. The code could then look similar to the following example:

```js
if(provider.hasColumnInstances('mystring')) {
  provider.removeDesc('mystring');
}
```

@puehringer and @sgratzl Would that work for you? Any other suggestions?

**Comment by puehringer** [comment]
The `ACommonDataProvider` has the following methods: 
```
    /**
     * adds another column description to this data provider
     * @param column
     */
    pushDesc(column: IColumnDesc): void;
    clearColumns(): void;
    getColumns(): IColumnDesc[];
    findDesc(ref: string): IColumnDesc;
```
Therefore, for the `removeDesc`, it would be sufficient to support `column: IColumnDesc` as parameter as the *lookup* already exists. 

Regarding the `column` property: I don't think that is actually part of LineUp (but rather `tdp_core`).

**Comment by sgratzl** [comment]
> @sgratzl Could it be that the `column` property is missing in the `IColumnDesc` interface?

no, not every column is a `ValueColumn` such as any composite column which doesn't have a column. Moreover, the column is converted to an generic access in an early stage such that the core (model classes, renderers, ...) don't know anything about a column property. 

>     findDesc(ref: string): IColumnDesc;

is intended for in internal use only when it comes to dumping/restoring
