### ISSUE TITLE
String column: Changing the group criteria does not trigger `groupCriteriaChanged` event

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#354]
* Release number or git hash: 6f329e6088f73cc8409f4ae639f76ff85430a5dd
* Web browser version and OS: Chrome 83

### Steps to reproduce

For detailed instructions see https://github.com/datavisyn/tdp_core/issues/379

### Observed behavior

Currently the `groupCriteriaChanged` event is only triggered for the first time the grouping is enabled. If a different grouping mode is selected, no further event is triggered.

![ordino-group-by-session](https://user-images.githubusercontent.com/5851088/84902015-89252d80-b0ac-11ea-8c5e-5b2bbebf75ba.gif)

### Expected behavior

Selecting a different grouping mode for the String column should trigger the `groupCriteriaChanged`.

**Comment by thinkh** [comment]
I commited a Cypress test that counts the `groupCriteriaChanged` event listener.

https://github.com/lineupjs/lineupjs/blob/a1f0aa74bcfe7e19c9a683cd86d2fb3f3ff3c4e4/cypress/integration/issue-354_string-column-group-change-event.spec.ts

**Comment by sgratzl** [comment]
why should this event be fired, the group criteria order hasn't changed? it is still a StringColumn. However, the grouping itself changes, and it will fire a corresponding `dirtyOrder` event with the reason `group_dirty`

**Comment by thinkh** [comment]
Ok, thanks for explaining. We will try the solution with `groupingChanged` on `StringColumn`.

**Comment by thinkh** [comment]
Thanks for the hint that worked for us. 👍
