### ISSUE TITLE
How to dump/persist the group aggregation status and avoid circular references? 

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#357]
We want to persist the expand/collapse action of groups in the provenance (see https://github.com/datavisyn/tdp_core/issues/378). The `LocalDataProvider.EVENT_GROUP_AGGREGATION_CHANGED` event provides the list of affected groups. However, when applying `JSON.stringify(groups)` we get a circular reference error:

```
LocalStorageGraph.ts:133 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'parent' -> object with constructor 'Object'
    |     property 'subGroups' -> object with constructor 'Array'
    --- index 0 closes the circle
    at Object.stringify (<anonymous>)
    at LocalStorageGraph.addNode (LocalStorageGraph.ts:133)
    at ProvenanceGraph.initAction (ProvenanceGraph.ts:428)
    at ProvenanceGraph.createAction (ProvenanceGraph.ts:422)
    at ProvenanceGraph.ts:474
    at ProvenanceGraph.inOrder (ProvenanceGraph.ts:585)
    at ProvenanceGraph.pushWithResult (ProvenanceGraph.ts:473)
    at Object.<anonymous> (cmds.ts:802)
    at Dispatch.apply (dispatch.js:61)
    at fireImpl (AEventDispatcher.ts:121)
```

The circular reference occurs due to the recursive group structure with `parent` and `subGroups`.

(I could not provide a CodeSandbox due to issue https://github.com/lineupjs/lineupjs/issues/355).

---

I checked the data provider and saw that there is some `restore()` and `dump()` functionality available:

https://github.com/lineupjs/lineupjs/blob/07cadb23643d0bac5d95cc955c5cfb180debc6ec/src/provider/ADataProvider.ts#L616

https://github.com/lineupjs/lineupjs/blob/07cadb23643d0bac5d95cc955c5cfb180debc6ec/src/provider/ADataProvider.ts#L663-L670

The problem here is that the `aggregations` property is private and there is no getter or setter available.

https://github.com/lineupjs/lineupjs/blob/07cadb23643d0bac5d95cc955c5cfb180debc6ec/src/provider/ADataProvider.ts#L208

Hence, the only (ugly) workaround I see at the moment would be to dump the whole data provider and pick only the `aggregations` property from the dump.

---

@sgratzl Is there any alternative how we can persist and restore the aggregated groups?

**Comment by sgratzl** [comment]
Taking the aggregations map won't work, since it is designed to be column/ranking id specific. Restoring a dump will ensure that but not a new LineUp instance.

**Comment by thinkh** [comment]
> Taking the aggregations map won't work, since it is designed to be column/ranking id specific. 

So the only option is that we flatten the group tree and restore the data structure?

> Restoring a dump will ensure that but not a new LineUp instance.

What do you mean by "not a new LineUp instance"?

**Comment by thinkh** [comment]
Ah, I think you posted a solution in this PR https://github.com/lineupjs/lineupjs/pull/363?

**Comment by sgratzl** [comment]
take a look at https://github.com/lineupjs/lineupjs/commit/8a4ff434ba47939d50f9facd77024ffa4054b226 for a sample store and restore of aggregation state

**Comment by thinkh** [comment]
Thanks for the helpful Cypress test. I compiled your branch (because of the changes in _ADataProvider.ts_) and used the build in Ordino. I adapted our initial implementation according to your Cypress test, so that we persist the group names and retrieve the actual categories on restore. I still have two bugs that seem to be caused by LineUp and a question.

## Restore missing value group

### Steps to reproduce

Prerequisite: The ranking must contain some missing values.

1. Add group information column (to see the group name and size)
2. Group by a column
3. Collapse all groups (group names: `["female", "male", "Missing values"]`)
4. Restore all groups (group names: `["female", "male", "Missing values"]`)

### Observed behavior

When restoring the missing value group (in the categorical column) shows the wrong category. The group name itself is correct and also the histogram in for the other categorical columns seem to be correct (or at least different). 

Only when I run the grouping step again, the missing value group is displayed correctly after collapsing all groups.

![lineup-restore-missing-value-aggregation](https://user-images.githubusercontent.com/5851088/85406663-6d190480-b562-11ea-91fd-5c054e83c913.gif)

My guess is that this is a bug in the renderer and not in the data provider.

### Expected behavior

The label of the missing value category should be correct when restoring the groups.

---

## Aggregate multiple levels

Beside the missing value group the persist/collapse of a single aggregation level works fine. 

![lineup-two-levels-aggregate-lowest](https://user-images.githubusercontent.com/5851088/85407660-c33a7780-b563-11ea-85a0-0b62566be90b.gif)

However, when working with two levels the aggregation of the first/highest level does not work.

### Steps to reproduce

1. Group by gender
1. Group by tumor type
2. Collapse the `female` group (group names: `["female"]`)
3. Restore expanded state

### Observed behavior

![lineup-two-levels-aggregate-highest](https://user-images.githubusercontent.com/5851088/85408881-6770ee00-b565-11ea-98c1-1c571af445c3.gif)

Restoring the highest aggregation level does not work, because the group objects cannot be found by its name.

https://github.com/lineupjs/lineupjs/blob/6985f0ef32ad081cb7873965f7548594c885ada3/cypress/integration/restore_aggregation_state.spec.ts#L58

https://github.com/lineupjs/lineupjs/blob/6985f0ef32ad081cb7873965f7548594c885ada3/cypress/integration/restore_aggregation_state.spec.ts#L64

Logging `ranking.getGroups()` reveals that the parent group with `female` is unavailable and only the subgroups like `adrenal gland carcinoma ∩ female`, `astrocytoma/glioblastoma ∩ female`, or `astrocytoma/glioblastoma ∩ male` are availabe. Hence, the only option is to traverse the group tree up and check the parents of all these categories.

@sgratzl Could you please extent the Cypress test with a second case that shows my use case with two aggregation levels?

---

## How to get the previous aggregation status?

At the moment I do not know how to retrieve/calculate the inverse value for the Top N case, since the event listener provides only the current value and no previous/backup value. 

https://github.com/lineupjs/lineupjs/blob/6985f0ef32ad081cb7873965f7548594c885ada3/src/provider/ADataProvider.ts#L125

https://github.com/lineupjs/lineupjs/blob/6985f0ef32ad081cb7873965f7548594c885ada3/src/provider/ADataProvider.ts#L797

Example:

* `aggregationStrategy: 'group+top+item'`
* Ranking shows top 10 for each group
* Expand top 10 to show all rows for the group (e.g., `{rid: 0, groups: "female", value: -1}`)

How do I get the inverse vaue (i.e., `value: 10`) in this case?

**Comment by sgratzl** [comment]
take a look at https://github.com/lineupjs/lineupjs/commit/0d931a1de0c6238eae2e4a652dc0ad68e6202c48

**Comment by thinkh** [comment]
@sgratzl Thanks for the implementation which was again very helpful!

I found an inconcistency which requires a workaround on my side (and should be fixed in the LineUp library in my opinion).

In you latest example you store the `previous` and `current` top N values in the `logs`. However, you never use the `previous` value to restore the old values. Instead you are reseting the ranking and restoring the `current` values. This works fine as the test also states.

However, in my case I want to restore the `previous` values, which can be a number array for multiple groups. Afterwards, I cannot restore this number array together with the groups array using `setTopNAggregated`, because the `value` parameter only accepts a single number.

https://github.com/lineupjs/lineupjs/blob/0d931a1de0c6238eae2e4a652dc0ad68e6202c48/src/provider/ADataProvider.ts#L788

My current work around is that use `previous[0]` to get only a single number which works fine as long all groups have the same value. I think, however, that `setTopNAggregated` should also accept a number array for the `value` parameter. Could you please change this?

---

Could also you please have a look at the **Restore missing value group** bug I described above? In my tests that bug is still present. Thanks.

**Comment by sgratzl** [comment]
> However, in my case I want to restore the `previous` values, which can be a number array for multiple groups. Afterwards, I cannot restore this number array together with the groups array using `setTopNAggregated`, because the `value` parameter only accepts a single number.

why not calling it N times instead?

**Comment by thinkh** [comment]
> why not calling it N times instead?

I tried this as well. The problem is that a lot of LineUp events are fired which I need to ignore in tdp_core and it triggers a LineUp re-rendering each group which decreases the performance drastically. Hence, applying the batch operation for multiple groups is the prefered way in my opinion.

**Comment by sgratzl** [comment]
see https://github.com/lineupjs/lineupjs/pull/364

**Comment by thinkh** [comment]
Thanks for the continous changes and improvements!
