### ISSUE TITLE
CircleCI auto update of lineupjs.github.io

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#366]
* Release number or git hash: c8a5808aa97fdae5bc73dfefeb08e21370dbb909
* Web browser version and OS: 

### Steps to reproduce

1. Merge a PR to develop branch (e.g., #364)
2. Triggers CircleCI auto update which commits https://github.com/lineupjs/lineupjs.github.io/commit/427f7133e5310b9a529a4168feec8bd26f9f407b
3. Open https://lineup.js.org/app_develop/

### Observed behavior

The demo https://lineup.js.org/app_develop/ page is not updated and still shows `v4.0.0` instead of `4.0.1-SNAPSHOT` (or similar).

### Expected behavior

The auto update should update the online demo at https://lineup.js.org/app_develop/. If https://lineup.js.org/develop/ should be the new correct path then this should work (at the moment I get an error 404).

### Possible solution

I assume that the build directory is moved to the wrong location:

https://github.com/lineupjs/lineupjs/blob/c8a5808aa97fdae5bc73dfefeb08e21370dbb909/.circleci/config.yml#L35

Correct might be `mv ../build "app_${CIRCLE_BRANCH}"` or similar.

See also both directories in https://github.com/lineupjs/lineupjs.github.io

![grafik](https://user-images.githubusercontent.com/5851088/85863147-08101980-b7c3-11ea-84d7-66fe40b6a642.png)

**Comment by sgratzl** [comment]
how is the app related to the library? lineup_app and lineupjs are independent entities and updating the library doesn't imply updating the app

**Comment by thinkh** [comment]
Got it. I was confused that both folders exists. Would it make sense to trigger a rebuild of the lineup_app `develop` branch, once something got merged into the lineupjs `develop` branch? Then the content of both folders (`develop` and `app_develop` would be consistent and the demo up-to-date.

**Comment by sgratzl** [comment]
I created https://github.com/lineupjs/lineup_app/pull/61 which would use LineUpJS as an externalish library. Thus, updating to the latest development branch would just mean to update some build files.

**Comment by thinkh** [comment]
Thanks, for the PR. If I see this correctly there is still some functionality missing that copies the build files from the `develop` directory into the `app_develop` directory, isn't it? Because the _LineUp.js_ and _LineUp.css_ files are still pointing to the build directory in the node_modules directory and to the `develop`.

**Comment by sgratzl** [comment]
yes but that would have to be part of the lineupjs repo. Moreover, I'm not fully sure whether it is the best idea

**Comment by thinkh** [comment]
> Moreover, I'm not fully sure whether it is the best idea

Why?
