### ISSUE TITLE
Unify missing value label for categorical filter in sidebar and dialog

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#369]
* Release number or git hash: v4.0.0
* Web browser version and OS: Chrome 83

### Steps to reproduce

1. Open https://lineup.js.org/app_develop/#soccer
2. Open filter dialog for categorical column

### Observed behavior

**Filter dialog**

> Filter rows containing missing values

![grafik](https://user-images.githubusercontent.com/5851088/85869336-d485bd00-b7cb-11ea-9a35-a626b218d46f.png)

**Filter in side panel**

> Filter 0 missing value rows

![grafik](https://user-images.githubusercontent.com/5851088/85869472-03039800-b7cc-11ea-88be-b0f386964e81.png)

### Expected behavior

The filter dialog should show the same text as in the side panel.

> Filter XXX missing value rows

**Comment by thinkh** [comment]
Additionally, if there are 0 missing values the checkbox in the side panel is disabled, but in the filter dialog it is not. Please unify this behavior as well.

**Comment by sgratzl** [comment]
the side panel shows a histogram, thus the current values. The filter dialog is data independent so far. Similarly, it doesn't state how many CF and W values exist but just shows the categories. Thus, just changing the number of missing rows would lead to another inconsistency.

**Comment by thinkh** [comment]
I understand your point that the filter dialog is data independent, but it is also inconsistent with the filter dialog of the number and date column (which are histograms). 

![grafik](https://user-images.githubusercontent.com/5851088/86025673-c4214c80-ba2e-11ea-9e1a-8b565873b885.png)
![grafik](https://user-images.githubusercontent.com/5851088/86025861-064a8e00-ba2f-11ea-924b-fadc366ded22.png)

How much effort is to bind the dialog to the data and show the number of missing values? Since you suggested the opportunity, we could also state the size of the category behind the name (e.g., `CF (125)`, `W (12)`).
