### ISSUE TITLE
Disable aggregation of neighboring groups with active group sorting

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#372]
* Release number or git hash: https://github.com/lineupjs/lineupjs/commit/daaec7bc6e4fccbf0c61a2bd1e1cbb84ed047f80
* Web browser version and OS: Chrome 83

### Steps to reproduce

1. Open https://lineup.js.org/develop/group.html
2. Group by _Cat_
3. Group by _Cat Label_
4. Sort groups by _#A_ and _Max_ (the selection might vary due to the randomness of the data)
5. Collapse first aggregation level (_Cat_)

### Observed behavior

It looks like the grouping algorithm tries to collapse groups as much as possible. In the following example the neighboring groups C3-C1 and C3-C2 are aggregated and collapsed to C3. All other groups, however, are not aggregated further and remain separated (e.g., C1-C1, C2-C2).

![grafik](https://user-images.githubusercontent.com/5851088/86053189-6c97d680-ba58-11ea-91bd-43a6b34f00d0.png)

### Expected behavior

For a user this behavior is confusing and might lead to mistakes while browsing the data. It would be helpful if we can turn off the aggregation of neighboring groups when the group sorting is active.

If the group sorting is inactive the aggregation is fine and helpful (see below).
 
![grafik](https://user-images.githubusercontent.com/5851088/86054062-c220b300-ba59-11ea-8e18-90812196ddce.png)

Is there already a setting or config value to achieve this behavior?

**Comment by sgratzl** [comment]
>  if we can turn off the aggregation of neighboring groups when the group sorting is active.

so if any group sorting criteria is set, no group tree should be extracted and merged
