### ISSUE TITLE
Aggregation's collapse/expand button clickable area is wrong

### ISSUE THREAD

**Issue by oltionchampari** [lineupjs/lineupjs#373]
* Release number or git hash: 
* Web browser version and OS: Chrome 83

### Steps to reproduce

1. Open ranking
2. Group by `categorical`, `string`, `number` columns
3. Try to collapse/expand the 3rd group in the aggregation column. 

### Observed behavior
The clickable area of the collapse/expand button is not where it should be, making it hard to collapse the groups

![click_area_bug.gif](https://images.zenhubusercontent.com/5cf50109d8501ed6b9d4b966/14c232a0-83d8-4983-8646-af93b80aaf72)
### Expected behavior

* The button's clickable area should be where the button is.

**Comment by sgratzl** [comment]
the column is too narrow. have you tried to increase its width?

**Comment by oltionchampari** [comment]
> the column is too narrow. have you tried to increase its width?

I could do that, but that would not scale.

If the width of the column is bigger than the width of the rows then everything works as expected but since i can group by as many times as i like at some point the width of the row with surpass that of the column causing the bug.

![row_width](https://user-images.githubusercontent.com/51322092/86324064-43389f80-bc3e-11ea-9fed-3cae771347dd.png)


I was wondering if there would be way to prevent this. We could for example widen the column along with the rows.
@thinkh  What do you think?

**Comment by thinkh** [comment]
> We could for example widen the column along with the rows.

I think that is a good idea. The only drawback could be that shifting whole ranking to the right might confuse users. But in my opinion it outweighs the initial issue that the user sees the arrow, but cannot click it.

@sgratzl Could you please try to implement the behavior described above: The aggregation column should grow in width once the grouping hierarchy has 3+ criteria. I'm not sure at the moment whether the column should shrink again once the hierarchy has less criteria or keep the bigger width. The default width should fit for two grouping criteria (= current behavior).
