### ISSUE TITLE
How does the group sorting work for categorical columns?

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#374]
I was discussing the group sorting the other day with a customer and we could not come up with a comprehensible explanation how the group sorting is working for categorical columns. Maybe you can help us here.

### Steps to reproduce

1. Open https://lineup.js.org/develop/group3.html
2. Collapse by third aggregation level
3. Add sort groups by for _Cat4_

### Observed behavior

Without group sorting (i.e., aggregation only) the pattern of the groups is clear and follows the group hierarchy. 

![grafik](https://user-images.githubusercontent.com/5851088/86091020-7565c800-baab-11ea-9267-d29304202d18.png)

However, once I sort the groups by _Cat4_ the pattern looks totally different. The groups do not follow the group hierarchy, but it is also not obvious that they are sorted by _Cat4_. There is a slight pattern that the groups are first sorted by `d1` and then `d2`, but the sorting criteria itself is not obvious.

![grafik](https://user-images.githubusercontent.com/5851088/86092816-54eb3d00-baae-11ea-884f-18ce2d1aa394.png)

### Question

@sgratzl Could you please explain how the groups are sorted in this example? 

P.S. We discuss the group sorting also in PR https://github.com/lineupjs/lineupjs/pull/273#pullrequestreview-381192393, but I did not sort the groups by a categorical column that is not used in the group hierarchy.

**Comment by sgratzl** [comment]
it is sorted by the most frequent category in the histogram of cat 4. In the upper half it is the blue ones in the lower ones it is the orange ones

**Comment by thinkh** [comment]
Thanks for the clarification. I close this issue for now and reopen it if necessary.
