### ISSUE TITLE
Handle missing values in Boolean column 

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#387]
* Release number or git hash: v4.0.0
* Web browser version and OS: Chrome 84

### Steps to reproduce

1. Open https://codepen.io/thinkh/pen/RwrzLqV?editors=1111

### Observed behavior

![grafik](https://user-images.githubusercontent.com/5851088/88890616-2940ab80-d242-11ea-8545-082e078adc40.png)

![grafik](https://user-images.githubusercontent.com/5851088/88890578-1a59f900-d242-11ea-8297-25aac4b38bc4.png)

Missing values are rendered as `false`. 

![grafik](https://user-images.githubusercontent.com/5851088/88890688-437a8980-d242-11ea-948d-dba94d1ac79a.png)

There is no histogram and also no option to filter out missing values.

### Expected behavior

* Render missing values with a missing value dash
* Use categorical filter dialog
* Use categorical histogram

**Comment by thinkh** [comment]
@sgratzl Can you fix/implement this ticket or do you need further input?

**Comment by sgratzl** [comment]
why not just declaring the column as a categorical column instead of a boolean column?

**Comment by thinkh** [comment]
Reasons:

1. The dataset contains boolean values and the BooleanColumn is the correct column type for this data type
2. `asLineUp()` detects and uses the BooleanColumn for this data type (otherwise it would require another pre-processing step to convert boolean into strings or similar).
