### ISSUE TITLE
Add filter option to selection column

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#394]
Currently the selection column can only be grouped and sorted. 

![grafik](https://user-images.githubusercontent.com/5851088/97599541-674b9800-1a08-11eb-880f-97be408801fd.png)

It would be interesting to filter the ranking by the selection column. The user should be able to select to show/hide the selected or unselected rows. Probably the filter dialog would look similar to the boolean column filter dialog (but without the missing values).

![grafik](https://user-images.githubusercontent.com/5851088/97601011-f86f3e80-1a09-11eb-910b-366768a210b9.png)

### Open questions

* Can the filter be re-evaluated/applied each time a row is selected/unselected? Example: The filter is applied to show only the selected rows. I would expect that a previously selected row gets hidden, once the user unselects the row.

**Comment by thinkh** [comment]
* Drill down use case
* Filter must be applied manually
* Filter dialog should only inform that unselected rows will be hidden, when applying filter.
* Reset action: resets all filter

**Comment by sgratzl** [comment]
so to clarify, when the user applies this filter, it will snapshot the currently selected rows and filter to only show this snapshot. Should the filter be the selected rows or the selected and visible rows which can be a different subset depending on the other filters?
