### ISSUE TITLE
Swap range slider of numerical filter for inverted data mapping

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#397]
* Release number or git hash: v4.1.1
* Web browser version and OS: Chrome 86

### Steps to reproduce

1. Open https://lineup.js.org/app_develop/#soccer
2. Age column -> more menu -> Data Mapping -> Inverted -> apply changes
3. Filter numerical filter by dragging the maximum border

### Observed behavior

Default range and histogram:

![grafik](https://user-images.githubusercontent.com/5851088/99425345-0296a580-2903-11eb-9dc9-687830ce4c03.png)

With inverted data mapping:

![grafik](https://user-images.githubusercontent.com/5851088/99425516-396cbb80-2903-11eb-911b-843bd25864d0.png)

* The histogram and range in the column summary is inverted -> correct
* The histogram in the side panel is inverted, but the ranges are not -> incorrect

It becomes even stranger when applying a filter:

![grafik](https://user-images.githubusercontent.com/5851088/99426169-12fb5000-2904-11eb-8d07-c1a61473ac98.png)

* The filter itself works correctly, all rows with a value > 22.80 are hidden
* The histogram in the column summary and side panel are correct
* However, it is confusing to drag the maximum range slider and the values are hidden to the left

The same applies to the filter dialog:

![grafik](https://user-images.githubusercontent.com/5851088/99426598-95840f80-2904-11eb-926e-30bae39647ab.png)

### Expected behavior

I'd expect that the interactive filter is also inverted with the data mapping. Consequentially, the minimum and maximum range slider and the values below must be swapped. Then the behavior and representation would be correct again.

**Comment by sgratzl** [comment]
There always have been an mismatch between the histogram, filter, and bars. 

As far as I remember, the filter operates on the data domain, whereas the bars and histogram operate in the normalized domain. In cases such as the inverted mapping this is directly visible as you have noted. 

Thus, filtering the top X values in the data domain, will filter out the lowest X in the inverted normalized domain. While we can fix it for this simple inverted case, I don't know a general solution that works with arbitrary mapping methods.
