### ISSUE TITLE
lineup sideview "Add Column" and Enter Reloads whole page

### ISSUE THREAD

**Issue by ginihumer** [lineupjs/lineupjs#417]
* Release number or git hash: 4.1.1
* Web browser version and OS: Google Chrome Version 89.0.4389.72; Windows 10

### Steps to reproduce

1.  open minimal usage example in code pen: [https://codepen.io/sgratzl/pen/Ozzbqp](https://codepen.io/sgratzl/pen/Ozzbqp)
2. click on "Add Column" in side view
3. press Enter

### Observed behavior

* Reloads whole page

### Expected behavior

* it should not do anything because no column is selected
* probably due to this part of the code:
![image](https://user-images.githubusercontent.com/45741696/110113257-26e39880-7db3-11eb-88da-604202bfe918.png)

**Comment by thinkh** [comment]
@ginihumer Thanks for the bug report. I can confirm this bug also with the [demo](https://lineup.js.org/app_develop/?#soccer).

@sgratzl Can you please have a look and file a fix PR?
