### ISSUE TITLE
How to generate a pre-defined filter on Categorical Columns?

### ISSUE THREAD

**Issue by shahpranavpks** [lineupjs/lineupjs#419]
I want to add a shortcut settings button on my page. This button's task is to sort, filter, and group the data with a single click. 

Using the buildanking(), I was able to sort and group. But how do I implement a pre-defined filter on a particular column?

The only option I can think of is filtering the input data and passing it to the builder. But then the reset button on the right panel won't work to reset the entire data (I assume). And I will have to reload the page with new data to reset everything.

Any suggestions on how to add a filter along with sort and groupBy?

**Comment by thinkh** [comment]
The filter is always applied to a specific column while sort and groupBy are applied to a ranking. Hence, you must first get the categorical column you want to filter from the ranking (e.g. using [`Ranking.find()`](https://github.com/lineupjs/lineupjs/blob/e1383eb5d3e99e26036e49b2cf606ce4a3a6b22e/src/model/Ranking.ts#L850-L859)) and then pass an [`ICategoricalFilter`](https://github.com/lineupjs/lineupjs/blob/f5cd5f2b9a884478dcffeb9679f5f799e1021fa5/src/model/ICategoricalColumn.ts#L91-L94) to [`CategoricalColumn.setFilter()`](https://github.com/lineupjs/lineupjs/blob/f5cd5f2b9a884478dcffeb9679f5f799e1021fa5/src/model/CategoricalColumn.ts#L245-L254).
