### ISSUE TITLE
Frozen columns are incorrectly shifted if "slow" columns are present

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#420]
* Release number or git hash: 93928a609013d4afd905c598b25dd125e6df1332
* Web browser version and OS: Chrome Version 89.0.4389.90 (Official Build) (64-bit), Windows 10 (and others...)

### Steps to reproduce
Have a ranking with many columns/columns that take longer to render (i.e. NumbersColumn with many numbers for example).
This consistently occurs when changing the data generation to something more expensive in the `frozen.html`:
```javascript
    for (let i = 0; i < 1000; ++i) {
      arr.push({
        s: 'Row ' + i,
        a: Math.random() * 10,
        test1: Array(1000).fill(null).map(() => Math.random() * 10),
        test2: Array(1000).fill(null).map(() => Math.random() * 10),
        test3: Array(1000).fill(null).map(() => Math.random() * 10),
        cat: cats[Math.floor(Math.random() * 3)],
        d: new Date(Date.now() - Math.floor(Math.random() * 1000000000000))
      });
    }
```

### Observed behavior
If the ranking is horizontally overflowing and one scrolls to the right, it often happens that the frozen columns not frozen anymore, i.e. the `.le-frozen .le-shifted` cells have a negative `left` property. The columns however stay positioned as they should be. 

![lineup_frozen](https://user-images.githubusercontent.com/51900829/111961481-67e8e600-8af1-11eb-88d2-64f20f65b101.gif)

### Expected behavior
Frozen columns (and cells of those) should stay frozen regardless of how something is scrolled.

**Comment by sgratzl** [comment]
see also https://github.com/lineupjs/lineupengine/pull/29

**Comment by puehringer** [comment]
@sgratzl I tested lineupjs/lineupengine#29 with my issue and it seems to fix everything.
