### ISSUE TITLE
Publish build of develop branch to npm

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#422]
With the merge of #410 into the develop branch and the switch to yarn we are experience build errors on our side.

The error occurs because we are using npm (instead of yarn) and using/building lineup directly from the develop branch. We could decouple and avoid this error when using the compiled JS also for the develop branch.

@sgratzl Could you please configure the GitHub action to automatically publish the JS files of the yarn build to npm? For the develop branch the release could be marked with a `next` tag (similar to [typescript](https://www.npmjs.com/package/typescript)).

Then we are able to always use the npm version instead of building from the develop branch.

**Comment by sgratzl** [comment]
I just manually published https://github.com/lineupjs/lineupjs/releases/tag/v4.2.0-alpha.0

**Comment by thinkh** [comment]
Thanks for the quick fix. 👍  We will check the develop build tomorrow morning. If it works I will remove the blocker label and replace the bug with a feature request, because publishing the develop branch automatically on npm is still useful.
