### ISSUE TITLE
weird behavour when setting visibility of column to false programmatically

### ISSUE THREAD

**Issue by ginihumer** [lineupjs/lineupjs#449]
When I add a column with the column builder and I set ".custom('visible', false)" then the column is not shown, as expected. however, if I try to reorder the columns, the behaviour is unexpected. The weird behaviour also occurs when trying to do create a group with two columns.

**To Reproduce**

1. open the advanced example in CodePen: [https://codepen.io/sgratzl/pen/vppyML](url)
2. change the line '.column(LineUpJS.buildStringColumn('d').label('Label').width(100))' to '.column(LineUpJS.buildStringColumn('d').label('Label').width(100).custom("visible", false))'
3. try to move column "Cat" to the space between columns "Cat2" and "A"
4. column "Cat" stays at its position, however columns "Cat2" and "A" switch positions.

**Expected behavior**

I would expect that column "Cat" would be repositioned between "Cat2" and "A"

**Screenshots**

![lineup-bug](https://user-images.githubusercontent.com/45741696/122007462-3d3cbf80-cdb8-11eb-9213-e74da5ee4dea.gif)

**Context**

- Version: how to see version in codePen?
- Browser: Google Chrome Version 90.0.4430.212

**Additional context**

**Comment by sgratzl** [comment]
why is the purpose of setting the column visibility to "false" in your example?

**Comment by ginihumer** [comment]
this bug only occurs, if the visibility is set to "false" for some column

**Comment by sgratzl** [comment]
I mean why do you change the viability at all? I cannot think of a use case where I need a hidden column that is still part of the ranking

**Comment by ginihumer** [comment]
so that users can add it over the sidepanel, if they really want to see it.
maybe I misunderstood the functionality of the "visibility"-property?

**Comment by sgratzl** [comment]
take a look at https://github.com/lineupjs/lineupjs/blob/9169b5dcbf663db658569f75bc5561a316cd2bae/demo/builder2.html#L27-L43

bulding a LineUp instance consists of two steps
 1. defining the columns = column descriptions
 2. defining the rankings = which are visible to the user having a subset of the defined columns and composite columns. 

For convenience reasons the second step is optional and if not given in the builder it will add a default ranking = all columns. So, in your case you need to define a custom ranking which doesn't include the columns that you don't wanna show at the beginning. The side panel will list all defined columns from step 1

**Comment by thinkh** [comment]
@ginihumer Does Sam's comment helped you? Can we close this issue?

**Comment by ginihumer** [comment]
Yes, that solves it. Thanks and sorry for the late reply.
