### ISSUE TITLE
Frame of selection highlight is not rendered on right side

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#456]
See image: 
![image](https://user-images.githubusercontent.com/2039375/126637878-5775b03e-0674-4238-805f-be151d9f2909.png)

The frame is not a full rectangle, the right side is missing. 

**To Reproduce**

Select either in aggregated or individual mode. 

**Expected behavior**

A full rectangle should be drawn.

**Comment by thinkh** [comment]
Will be fixed with PR https://github.com/lineupjs/lineupengine/pull/40.
