### ISSUE TITLE
Boxplot whisker ends shown for aggregated groups even if values are exceeding the maximum set by “data mapping”

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#483]
**To Reproduce**

1. Open https://lineup.js.org/develop/aids.html
2. Group for Human Development Index
3. Collapse all groups
4. Open data mapping for column _Yearly change in %_
5. Set max value of input domain to 2.5

**Expected behavior**

The Boxplot whisker ends (right border) should not be visible if data mapping is applied.

**Screenshots**

Before adjusting the data mapping

![grafik](https://user-images.githubusercontent.com/5851088/137992463-030b85b9-f34d-42b2-9587-befcef72acc3.png)

After adjusting the data mapping

![grafik](https://user-images.githubusercontent.com/5851088/137992587-78ae4555-7b77-457b-85ec-a592dbd2b40f.png)

The whiskers are "off-screen" (or column) but here they are still visible which leads to wrong interpretations of the data.

**Context**

- Version: 4.3.0
- Browser: Chrome 94

**Comment by thinkh** [comment]
Thanks for explanation. What would happen if we disable the clamping for data mapping? Which other side effects does this have in LineUp?

**Comment by sgratzl** [comment]
So, that the basic assumption that a normalized value is in the 0..1 range won't hold anymore...
 * all renderer that are using normalized values would need to manually handle that case ensuring that they are not rendering outside of their box
 * not sure about normalized histograms and making sure that the alignment to the data mapping is still the same
 * combined columns will have the same problem, e.g. a stacked bar where one component is bigger that 1 or in theory also smaller than 0
 * numerical color scales that use the value would also need to be adapted.

**Comment by thinkh** [comment]
We discussed this internally and we suggest to show a warning to the user in the data mapping dialog when modifying the input domain.

> Warning: All items with values outside of the input domain will be set to the min/max value of the input domain.

![grafik](https://user-images.githubusercontent.com/5851088/146088684-5f060513-0a6d-494a-a8ee-c35d397e749c.png)

@sgratzl Is it possible to show such a warning?
