### ISSUE TITLE
Default Vis for categorical column with large N: Text

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#490]
We only show the text labels, no visualization in the rows.

**Comment by sgratzl** [comment]
there is already the "String" renderer for categorical columns:

![image](https://user-images.githubusercontent.com/4129778/142883882-b5553269-6328-4d81-9068-2d306e5fd975.png)


not sure what to do for this ticket

**Comment by alexsb** [comment]
OK, makes sense, closing. This issue originally had details on how the header should work, but based on discussions we had this was edited out, leaving only the unnecessary stub.
