### ISSUE TITLE
Add a clear selection button to the selection column 

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#501]
Title says everything; it's hard to clear a selection right now. 

Alternatively, this could go into the overall toolbar.

**Comment by sgratzl** [comment]
you have the option to just click the "select" all checkbox twixe (select all and then deselect all). 

Alternatively in LineUp I made that the selection indicator on the side panel allows to clear the selection, when you click on it. We could do a similar thing

![image](https://user-images.githubusercontent.com/4129778/142558855-7190bb9b-b4c6-4344-9fa7-f43b47e3e48e.png)

**Comment by alexsb** [comment]
I like the selection clear option on the right; I'd also add an explicit clear selection button to the context menu of the selection header
