### ISSUE TITLE
Webpack error with 4.3.0

### ISSUE THREAD

**Issue by ap--** [lineupjs/lineupjs#517]
Hello everyone,

I have a quick question that might be a user error from my side, but I am not familiar enough with the Javascript ecosystem to be 100% sure that it's not.

When I install lineup 4.2.0 for my app and package the app via webpack, everything works.
When I upgrade to 4.3.0 I get the following error from webpack:

```
Module not found: Error: Exports field key should be relative path and start with "./" (key: ".pnp.cjs")
```

Which seems to be due to:
https://github.com/lineupjs/lineupjs/blob/6a6a7244b87ed33538d4efccd727efe933ba998d/package.json#L49

Am I missing some tooling that's required for 4.3.0 to be packaged via webpack?

**Context**

I'm running npm 8.1.0 and webpack 5.62.1

Cheers,
Andreas 😃

**Comment by sgratzl** [comment]
has been fixed with https://github.com/lineupjs/lineupjs/pull/509
