### ISSUE TITLE
Adjust darkness for various elements

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#525]
Here's an image with the new proposed ticks: 

![image](https://user-images.githubusercontent.com/2039375/145815462-b62e4b6a-1af9-4b54-8893-661efe24c8ee.png)

Two things stand out to me: the dots and ticks aren't as prominent as the bars. And the NAN dashes are as prominent as the dots and tick. Both aren't great. Hence: 

* We should increase the darkness of the dots and ticks. They’re the same color as the bars, but have much less body. When ticks are shown in an aggregated cell, they should be lighter/more transparent though, so that we can see overplotting. 

* We should reduce the darkness of the NAN dashes and/or reduce the "height" of the dashes so that they are thinner.

**Comment by sgratzl** [comment]
note: besides the N/A indicators, the colors are driven by the color of the column

**Comment by alexsb** [comment]
Good point; we need a systematic solution for this. 

In our style guide we distinguish between lark mark and small mark colors: 

![image](https://user-images.githubusercontent.com/2039375/145991377-2b030c9f-8fd8-4bfd-a6e6-4342de8b4469.png)

So the marks should use the hue given by the column, but adjust the darkness according to the mark size.

**Comment by alexsb** [comment]
We agreed on the following solution: 

* A cell has a given color, for simplicity assume it is given a saturation value of 0.5 
* That value is either based on a color for all marks in the column, or is driven by a color mapping. 
* For a large mark, the saturation value is decreased by a value N, which we will have to experimentally determine, but a good starting point would be to decrease saturation by 20%
* For a small mark (dot, dash), the saturation value is increased by a value M, again, try increasing by 20% to start.  
* The NaN/None dash should be thinner and more desaturated, maybe at the same level as the large mark. 

We could also experiment with a bit of changing saturation for bars so that smaller bars are more saturated and longer bars are less saturated. But that change should be small and I'm not sure whether it'll work.

**Comment by sgratzl** [comment]
note: since gray values are in the form `hsl(0,0,76%)` this saturation change has no effect on pure gray columns.

**Comment by alexsb** [comment]
Good point. Then use lightness or alpha instead. Might be better anyways.
