### ISSUE TITLE
Selection checkboxes can be added to the ranking, but not removed

### ISSUE THREAD

**Issue by puehringer** [lineupjs/lineupjs#554]
When I add a selection checkbox column via the add column dialog, a selection column appears, but it cannot be deleted anymore (i.e. the option simply does not appear).  For rank columns (another support column), the removal works though. 

**To Reproduce**

1. Open arbitrary ranking
2. Add selection checkboxes
3. Try to remove the column again --> remove is missing

**Expected behavior**

Removal is possible.
The remaining question is if *only* manually added selection checkboxes should be removable, or all. I would keep it simple and allow users to remove the _initial_ selection checkboxes as well.

**Comment by sgratzl** [comment]
it was introduced by https://github.com/lineupjs/lineupjs/commit/c0a6170090927d2f4137362a5b63088b38e3def9
