### ISSUE TITLE
Error when using lineup in React app

### ISSUE THREAD

**Issue by heberleh** [lineupjs/lineupjs#567]
I'm trying to use the LineUp inside a react library but I'm getting an error:

> Uncaught TypeError: Cannot read properties of undefined (reading 'PureComponent')
>     at Module.<anonymous> (column.ts:28:98)
>     at r (bootstrap:19:22)
>     at bootstrap:83:10
>     at LineUpJSx.js:4:1188
>     at universalModuleDefinition:9:22
>     at universalModuleDefinition:1:1

Code:
```javascript
asLineUp(div, rows) //rows are the Cat example dataset from the README
```

LineUp version:

> "lineupjs": "^4.6.0",

My React version:
>   "peerDependencies": {
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2"
>   }
> 

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/4249107/167635572-48e3e292-564a-4729-b167-7adc1cba1ef9.png">

**Comment by heberleh** [comment]
Any ideas if this is  a problem of "containing" contexts/contaminated contexts?
Maybe some bootstrap thing? Do I need to import bootstrap?
With ` <div
                    style={{ height: "600px" }}                 
                    id="lineup_view"
                ></div>` I'm getting this strange behaviour:
            
                
<img width="796" alt="image" src="https://user-images.githubusercontent.com/4249107/167641230-52868a69-9d3e-4061-a7ea-b2539bd5409e.png">


If I don't set `height` in the `div`, it looks like this:
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/4249107/167643429-b24261a9-6c45-49f2-bae5-088bf372d4f8.png">

Setting `width` didn't help.

Module universal definition refers to this:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/4249107/167643620-c1c4085a-c1ae-47a0-87dc-370c5b5ebca8.png">


I'm importing the function like this:
`import { asLineUp } from "lineupjs";`

**Comment by sgratzl** [comment]
have you tried https://github.com/lineupjs/lineupjsx ?

**Comment by heberleh** [comment]
I tried to install both libraries and the two url all together, just in
case some would bring something was missing, but couldn't make it work.
Also checked CIME and the lineup_app... Couldn't figure it out.

The react version looked too difficult to guess how to do and change
things. A controller that is called on demand like in the js lib sounds
better and faster to get around. The lib already is very complex to code
with in the version with more examples. Examples would be another reason
not to use the react one.

I will need to do thinks like sorting groups (create groups from groups and
sort ), and so on. Currently the functionalities from the tool are not
enough so I will need to play around quite a bit.

Thanks for the your time and for the lib!

**Comment by heberleh** [comment]
With both npm libs installed and only the css in the index.html (url to script commented out), the error message in the console doesn't appear. However, the look is still awkward. Maybe something in my app... but still I don't understand what is the correct way of installing Lineup.

**Comment by heberleh** [comment]
As said, the error (red message in console) disappeared with commenting out the <script ..lineup> from index.html
I'm still trying to find out if it's my app our Lineup that has a problem.
Here is the reason why it is disaligned: there is a `.li-selection-indicator` with a `canvas` inside creating the space.
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/4249107/167848032-e78ae6b5-d770-4818-96a2-867be856c115.png">


Deleting that canvas seems to place it vertically correct:
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/4249107/167848205-88720755-bf91-4c02-bdb6-514494b1e0a9.png">

**Comment by heberleh** [comment]
All other "selection canvas" work except the left-line one if I set
`.lu-selection-indicator {
    display: none;`}

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/4249107/167852991-b12b97f7-7e3b-4684-9905-06cf131218fd.png">

**Comment by sgratzl** [comment]
minimal example how to use plain LineUp.js in React: https://codesandbox.io/s/cool-grass-yj0il5?file=/src/App.tsx:854-890
