### ISSUE TITLE
Categorical filter could also be based on what users write

### ISSUE THREAD

**Issue by heberleh** [lineupjs/lineupjs#568]
As a suggestion, when you have a big set of categories, users could benefit with a filter by regex/text.

Example:
If I have many types of animals, I could write dog and filter for all types of dogs.

Current situation, as of my understanding:
if I have 20 types of dogs among other 300 types of animals, users need to 'unselect' all categories and then select the 20 types of dogs among 300 animals. If the names have the word dog as suffix, prefix or root, it means that users need to really look for any word with the string dog in a big list of words (300).

**Comment by thinkh** [comment]
@heberleh Thanks for your suggestion. To me it sounds similar to [a previous issue](https://github.com/lineupjs/lineupjs/issues/405) I posted a while ago. Does that help you / resolve this issue?

**Comment by heberleh** [comment]
I see, yeah, it makes sense. What is missing is the visualizations that are currently missing in the text-type in the default lineup ui.

Can I activate this visualization in text-type column using different settings?

Although I have many categories, I may have small list of categories inside groups.
E.g., 200 categories divided into groups with 1 to 5 categories.
<img width="207" alt="image" src="https://user-images.githubusercontent.com/4249107/168023416-7b464a85-77b8-4b5f-8976-1a2cc77f09a9.png">

**Comment by heberleh** [comment]
It's also missing the colors to differentiate categories.

Although two different categories may end up with the same color... which is not ideal but different levels of opacity and the chances of 2 different categories displayed with same color will become minimal. Maybe glyphs would help here.

Maybe the only way to achieve that is by creating a new type or type of visualization. I will see what can be done. Thanks for the help and clarifications!
