### ISSUE TITLE
Error in scheduler.ts

### ISSUE THREAD

**Issue by oltionchampari** [lineupjs/lineupjs#570]
Check if `clearIdleCallback` is defined before calling it
see https://github.com/lineupjs/lineupjs/blob/93e18c26a61797342b4953a2d6b6a9558ce4a177/src/internal/scheduler.ts#L232-L233
This causes the error 

![grafik](https://user-images.githubusercontent.com/51322092/168582465-627c25e1-53ed-4185-b075-d7dd033464a1.png)

**Comment by sgratzl** [comment]
https://github.com/lineupjs/lineupjs/pull/521 will remove this code chunk
