### ISSUE TITLE
Highlight Background instead of Frame for Selections

### ISSUE THREAD

**Issue by alexsb** [lineupjs/lineupjs#574]
Frames are a little more brittle, we should use background highlighting. Here's a mock-up: 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/2039375/169818321-62093203-053c-411c-82fe-01bb855225e8.png">

Colors
Click: FFCF76
Hover: FFE8BE

**Comment by mstreit** [comment]
Yes, I also think that looks nicer. 
Before doing this, we should check some corner cases (e.g., partially selected histogram for numerical columns colored orange - see below).

![image](https://user-images.githubusercontent.com/4129755/169822387-c5304276-0230-4e0e-8491-ec8fc0a33092.png)

**Comment by alexsb** [comment]
you mean because of potentially clashing colors?

**Comment by mstreit** [comment]
Would be great to get this implemented soon.
