### ISSUE TITLE
Sorting a combined column behaves incorrectly

### ISSUE THREAD

**Issue by dvdanielamoitzi** [lineupjs/lineupjs#579]
When I create a combined column and try to sort it by one attribute, the bar visualization in the ranking is not displayed correctly sometimes.

**Expected behavior**

The bars should align correctly, even if one value is null.

**Screenshots**

![sorting-combined](https://user-images.githubusercontent.com/57343176/177613239-a319392f-5e31-448a-9cfb-98be4d0e4911.gif)

**Context**

- Version: I tried it in the current version of: https://lineup.js.org/app/#soccer
- Browser: Chrome

**Comment by sgratzl** [comment]
https://github.com/lineupjs/lineupjs/commit/810166fb0ebb1be25324de1bb4769c67ec128184 is showing a missing value if any of the stacked bar is missing. 

Thus, cannot reproduce
