### ISSUE TITLE
Dialogs are truncated and not scrollable when overflowing the browser viewport

### ISSUE THREAD

**Issue by thinkh** [lineupjs/lineupjs#664]
When I have a small browser window and open a long more menu, it is truncated and I cannot access the menu points at the bottom.

**To Reproduce**

1. Decrease the size of the browser window
2. Click on a more menu (e.g., of a numerical column)
3. Open another submenu

**Expected behavior**

The menu should overflow and show a scrollbar to access the last menu items that are now outside the viewport. Also the submenu should be fully accessible and/or scrollable.

**Screenshots**

![image](https://github.com/lineupjs/lineupjs/assets/5851088/b50b8af2-4f84-4556-aac7-23619c5d7549)

[lineup-menu-outside-viewport.webm](https://github.com/lineupjs/lineupjs/assets/5851088/915f2d57-1417-4967-9de7-a453fc5d00cf)

**Context**

- Version: v4.6.2
- Browser: Chrome 125

**Additional context**

**Comment by dvchristianbors** [comment]
Done.
